Linaro/squad

squad/core/tasks/__init__.py

This fixes invalid syntax error.
Signed-off-by: Luis Araujo <luis.araujo@collabora.co.uk>

Remove comma in metadata_fields

---

squad/core/comparison.py
squad/core/history.py
test/core/test_comparison.py
test/core/test_history.py

These changes will make it easier to spot case where a given test has no
results in some builds. This can be caused by issue with the builds that make
the test job fail before any tests are executed, so we miss results for them.
The test history page will now list all builds, not only the ones in which
there were results for the test in question.
Test comparison page will now list all tests from all projects, not only the
tests that were present in the builds being compared.

Make test history and test comparison more complete

---

squad/api/ci.py
test/api/test_ci.py

When request doens't contain required fields, 400 response is returned
instead of 500.
fixes #19

api/ci: check whether the submitted request is valid

---

squad/core/admin.py
squad/core/models.py

This allows deleting ProjectStatus object and re-triggering the email
notifications.

core: add ProjectStatus to admin interface

---

squad/ci/backend/lava.py

ci: allow resubmit 'Job' errors in LAVA backend

---

squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/models.py
test/ci/backend/test_lava.py
test/ci/test_models.py

Job logs are now fetched during data processing and are added to the
TestRun object.

ci: lava: fetch job logs in LAVA backend

---

squad/ci/backend/lava.py

Only top level metadata is used as job metadata. This fixes the problem
of overwriting the metadata by inline test definitions

ci: lava: fix metadata parsing

---

squad/core/models.py

To make front page navigation easier, Projects and Groups are not in
alphabetical order.

core: setup Project and Group ordering

---

squad/core/tasks/__init__.py
test/api/tests.py
test/ci/backend/test_lava.py
test/core/test_tasks.py

Because of change in postrges driver behaviour null bytes are no longer
allowed. They were found in metadata received from LAVA. This patch
removes null bytes to avoid database exception.

core: remove null bytes from TestRun metadata

---

squad/ci/models.py
test/ci/test_models.py

If a TestJob produces some results but the metadata suggest it's not
finished properly, mark is as 'completed' and allow resubmit. This way
email notifications engine can cope with jobs that produce results
despite LAVA reporting infrastructure issue.

ci: mark testjob completed if it produced results

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

When test job was canceled in LAVA the backend created TestRun which had
'completed' field set to true. This isn't correct as it would trigger
email reporting. This patch fixes the problem

ci: lava: report incomplete TestRun when TestJob is canceled

---

squad/frontend/templates/squad/group.html

Group template last updated column now uses the proper status object.
This commit fixes #70

frontend: fix group template

---

scripts/testdata/submit-test-data
squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt

Example plain text output (HTML output is equivalent):
| Failures
| ------------------------------------------------------------------------
|
| testenv:
|
|   * tgroup1/test1
|   * tgroup1/test2 -- never passed
|   * tgroup1/test3 -- failing since build 6, from July 17, 2017, 2:21 p.m.
|   * tgroup1/test4
|   * tgroup1/test5
Fixes issue #64

core/notification: clearly identify tests that never passed

---

squad/ci/models.py
test/ci/test_models.py

When LAVA reports TestJob as Complete but doesn't produce any result
this might be a result of LAVA bug. It might also be a legitimate
result, but LAVA CI backend of SQUAD doesn't support it. This patch sets
proper flags on TestJob and TestRun objects so the TestJob can be
resubmitted from UI.

ci: mark proper TestRun status on awkward LAVA failure

---

INSTALL.rst
squad/core/tasks/__init__.py
squad/core/tasks/notification.py
test/core/test_tasks.py
test/core/test_tasks_notification.py

These changes make notifications be sent as soon as there is enough data,
instead of relying on scheduled celery recurring task.

Instant notifications

---

squad/core/tasks/notification.py
test/core/test_tasks_notification.py

In some cases there could be a timing issue with notifications: a
ProjectStatus is created and a notification is triggered. The
notification request is handled by a worker process before the process
that requested the notification was able to commit the changes to the
database, and the new object is not yet visible to the worker process.
This assumes that id is autoincremented, otherwise a request for a
really unexisting ProjectStatus object would stay in a infinite loop.

core/notifications: retry if ProjectStatus id does not exist (yet)

---

squad/core/models.py
squad/core/tasks/__init__.py
test/core/test_project_status.py

When new results arrive, ProjectStatus object is updated and saved to
database. So all updates are preserved. Before this patch all updates
were lost because ProjectStatus wasn't saved to database.

core: fix update of ProjectStatus objects

---

squad/frontend/static/squad/charts.js

_.castArray is only available from lodash 4.4.0. We're using 2.4.1. This
is a temporary solution to allow the charts to work. It might cause some
side effects.

frontend: remove _.castArray from JS code

---

squad/ci/backend/lava.py

LAVA sometimes replies with XML-RPC error. In this case there is no
trace that something went wrong. The only indication is that some
results are missing in the frontend. This patch addresses the issue by
failing gracefully, saving error log to the TestJob.failure and sending
admin email notification.
Fixes #97

ci: lava: fail gracefully when LAVA replies with error

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

In order to work around the (possible) LAVA issue with saving results,
artificial delay in LAVA backend is introduced. It should give LAVA
enough time to save results in case there are plenty of them. This patch
should be reverted once LAVA problem is fixed or other source of this
issue is identified

ci: lava: introduce artificial delay in fetching results

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

If 'auto-login-action' is used, it can be associated with boot action.
This way lava backend can identify information about
successful/unsuccessful device boot. auto-login-action duration is
considered as overall boot time.

ci: lava: add artificial boot test result

---

squad/core/models.py
test/core/test_build.py

This can be used e.g. in custom email report templates.

core/Build: provide test suites executed by environment

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

ci: lava: add 'auto-login-action' to automatically resubmitted patterns

---

squad/core/models.py
test/core/test_build.py

Build method test_suites_by_environment will not only provide sorted
list of environments for each build but also test counts
(pass,fail,skip) for each testsuite in each environment

core: modify test_suites_by_environment to provide test count

---

squad/core/models.py
squad/frontend/templates/squad/_builds_table.html
squad/frontend/views.py

The build listings were way too expensive, consuming too much memory and
taking too long to run. This change drastically reduces both the number
of database queries and the amount of RAM needed to render the pages.

frontend: optimize build listings

---

squad/core/models.py
squad/frontend/templates/squad/_builds_table.html
squad/frontend/views.py
test/frontend/test_basics.py

This avoids unecessary noise with exceptions being generated for
unexisting objects.

frontend: return 404 on non-existing Build, TestRun, and Attachment

---

squad/core/notification.py
squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt

The full metadata is still available for use in custom templates, for
example.

core/notification: include only important metadata in emails

---

squad/frontend/static/squad/charts.js

When using a link generated for metrics, it doesn't work when sharing or trying to reopen. The graphs are missing. Sometimes the environments are not selected. Example:
https://qa-reports.linaro.org/qa/squad/metrics/?environment=travis-sqlite3&environment=travis-postgresql&metric=tests_per_sec
In this case environments are selected, but the chart is not displayed.

permalinks for metrics don't work

---

squad/core/notification.py

important_metadata dictionary is added to the notification context.

notifications: add missing important metadata dict

---

.gitignore
squad/frontend/static/download.conf
squad/frontend/static/main.css
squad/frontend/static/squad/table.js
squad/frontend/templates/squad/base.html
squad/frontend/templates/squad/test_history.html
squad/frontend/templates/squad/tests.html

Table headers are floating. It's easier to see the environment if the
list of results is long.

frontend: floating table headers

---

squad/ci/models.py
squad/ci/tasks.py
test/ci/test_models.py
test/ci/test_tasks.py

The poll() task was implemented in a way that Backend.poll() would
directly call fetch() on each test job that needs to be polled. However,
poll() has no exception handling, and therefore an issue with one of the
jobs would cause the entire poll operation to be aborted.
The fetch() task, on the other hand, already handles exceptions, and
does the right thing depending on whether the issue is a temporary or a
permanent one.
Convert Backend.poll() into a generator function that will yield all the
test jobs that should be fetched (instead of fetching them directly).
The actual fetching is then triggered in the background by the poll
task, so that each test job will have exceptions handled individually,
and an issue with one test job will not affect the rest of the test jobs
that are being …

ci: Reimplement poll as a series of fetch operations

---

squad/frontend/templates/squad/test_run.html
squad/frontend/templates/squad/tests.html

Test names in test run view and in all tests view are converted to links
showing the history of the test results

frontend: add links to test history

---

squad/ci/backend/lava.py
squad/core/admin.py

This PR fixes two issues that we are having in production:
- parsing the structured logs from LAVA is very slow when the the log is large
enough
- we were getting IndexError due to the assumption that result['suite'] from
LAVA always contains '_' characters.
I'm also including a small change to the ProjectStatus Admin to make it easier
to find ProjectStatus that should have been notified, but weren't.

Fetching issues

---

squad/core/queries.py

That code was from the time where we assumed that each build would only
have a single test run for each environment, which is no longer the
case.

core: fix query for "test pass %"

---

Procfile
squad/ci/admin.py
squad/ci/backend/lava.py
squad/ci/models.py
squad/core/tasks/__init__.py
test/core/test_tasks.py
test/integration/test_build_notification_from_ci.py

When a testjob was fetched, the ProjectStatus would be created *before* the
test job was saved to the database, which would cause `Build.finished` to be
False, and therefore the notification would never go out. To fix that, we delay
updating the project status until after the test job is completely persisted.
An integration test is being added alongside the fix.
There are also some commits doing cleanups and small improvements, moving
things around, etc.

Fix notifications for CI-based projects

---

squad/core/templates/squad/notification/failed_test_jobs.html
squad/core/templates/squad/notification/failed_test_jobs.txt

The templates were missing "group" in the URL and produced invalid
links.

core: fix failed testjob notification templates

---

squad/frontend/templates/squad/testjob.html
squad/frontend/views.py

In case test job doesn't have URL but has some failure registered, the
failure is presented to the user.

frontend: display testjob.failure if available

---

squad/core/notification.py
test/core/test_notification.py

If preview notifications don't get marked as already notified, admins
will receive one email per test job after the project timeout has
passed. We only want the admins to be notified once.
When a moderated notification is approved, the final notitification is
sent unconditionally, so it's OK to mark the project status as notified
as sent when sending the preview.

core/notification: don't spam admins

---

requirements.txt
squad/api/rest.py
squad/api/urls.py
squad/settings.py
test/api/test_rest.py

This is a basic implementation of a REST API using Django REST Framework. The
API root, /api, provides a browsable interface when accessed with a web
browser, and it can also display documentation. The actual documentation and
changes to make the API browser match the overall SQUAD layout (CSS, etc) will
be the subject of a subsequent pull request.

Add REST API

---

.gitignore
Procfile
doc/install.rst
requirements.txt
squad/settings.py

Support for RDBMS-based periodic tasks is being dropped. It was not being
heavily used, anyway, and can be added back in the future by adding a new
dependency or celery v4.

Upgrade to celery v4

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

LAVA 2018.1 allows to fetch test results in chunks. This makes possible
to retrieve data for test jobs with big numbers of test results. The
patch for squad makes use of this feature.

ci: fetch data in chunks in LAVA backend

---

squad/api/rest.py
test/api/test_rest.py

Allow for easier fetching of project status. Added calculated 'finished'
field to the Build object and reference to ProjectStatus.

api: Add ProjectStatus to REST API

---

squad/api/rest.py

Remove 'name' from excluded fields as this was causing server crash.

api: fix TestSerializer

---

doc/intro.rst
squad/core/utils.py
test/core/test_tasks.py

In some cases (Android CTS) test come with different variants. Test
variants are identified with [foo] at the end of the test name. The
string in the brackets can contain slashes.

core: add support for test case variants

---

squad/ci/backend/lava.py
test/ci/backend/example-lava-log.yaml
test/ci/backend/test_lava.py

LAVA presents the log as YAML document. We're only interested in the
'device' level logs. So all other logs are discarded. In other to do
this operation, YAML content has to be parsed. Loading the whole log
into memory caused OoM issues in the past. This patch uses incremental
parsing approach in order to avoid loading full yaml to memory.

ci: lava: parse LAVA log using incremental parser

---

squad/api/rest.py
test/api/test_rest.py

This will allow to view and change the custom email templates without
accessing admin UI.

api: add REST API for email templates

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

Due to changes in LAVA state machine, the ZMQ events contain 2 fields
representing jobs status: 'state' and 'health'. 'state' is responsible
for marking the job is running or not. 'health' represents the status of
finished job (Complete, Incomplete, Canceled). This patch adjusts the
logic in lava listener code to work with the new dictionary keys.

ci: lava: update listener to match new LAVA state machine

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

When there is no metadata in LAVA job definition, lava backend should
not crash during result fetching.

ci: lava: don't crash if there is no metadata

---

squad/ci/backend/lava.py

When resubmitting the job, old test run was assigned to new test job.
This created confusion in the web UI. This patch makes the testrun field
in TestJob object empty when resubmitting. Fixes #228.

lava: fix resubmit() function

---

squad/core/notification.py
squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt

Unfortunately, at the moment there is no good solution to keep the information
on "failing since" for tests that does not require an absurd performance
penalty. So one of the patches here drops that from the default template.

core/notification: performance improvements

---

squad/frontend/templates/squad/_project_list.html
squad/frontend/templates/squad/build-nav.html
squad/frontend/templates/squad/group.html
squad/frontend/templates/squad/index.html
squad/frontend/templates/squad/project-nav.html
squad/frontend/templates/squad/test_run.html
squad/frontend/templates/squad/test_run_suite_metrics.html
squad/frontend/templates/squad/test_run_suite_tests.html

This patch changes how the UI displays the object names. Instead of
displaying 'slug', 'name' is displayed. This allows for more free-form
strings to be displayed in the UI. Since 'name' fields are mandatory
for Group and Project objects there is no need to make the defaults.

frontend: display model.name instead of model.slug

---

squad/core/models.py

On my tests, the response time of a single request to the test history
page is cut in half.
Test.prefetch_related is used to load the associated objects for a list
of tests, what happens for example in the "test history" page. Not
preloading project and group data causes a N+1 query situation that
makes the test history page brutally slow.

core: fetch project and group for Test

---

squad/core/comparison.py
test/core/test_comparison.py

By that point we already have all the needed data loaded, so there is no
point in making an extra query to the database. Also, there were serious
flaws in that query:
- it selected *all* tests ever executed for all *projects* involved in
the comparison, which is way too broad and will hit *a lot* of data.
- it also applied a distinct(), what is not efficient in this case
One of the test cases was actually wrong, and is now fixed.

core/comparison: avoid extra, slow database query

---

squad/api/rest.py

The most important change is to make user_groups field of Group object
read_only. This prevents from accidentally removing all user groups when
making update. Other changes make the serializers more uniform across
all API.

api: minor fixes to make API more uniform

---

squad/frontend/tests.py
squad/frontend/urls.py
test/frontend/test_history.py

```
Traceback: 
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
41.             response = get_response(request)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
249.             response = self._get_response(request)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
187.                 response = self.process_exception_by_middleware(e, request)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/ht …
```

DoesNotExist at /group/project/tests/

---

squad/api/rest.py

It would make sense to order the builds page by the latest first.
https://qa-reports.linaro.org/api/builds/

api: order build results by ascending instead of descending

---

scripts/squad-config
squad/api/rest.py

I think I made it working in very basic cases. There are no tests for the script yet. It is likely there are bugs. I didn't test more complex features like adding group with projects inside.
Some operations are not supported for sure:
- managing UserGroups in Group object
- moving Projects across Groups
These 2 items would only be possible if object IDs were saved in the config file.
Work remaining to be done:
- support multiple config files (right now config has to be stored in single file)
- support external files for things like text input (to improve text formatting)
If the current approach is too complex (I think it is) we should consider other options. For example managing simple objects without any nested complex objects is fairly easy. Storing object IDs would make it way easier …

External config script

---

doc/intro.rst
requirements.txt
squad/frontend/urls.py
squad/frontend/views.py
test/frontend/test_basics.py

'badges' endpoint will help rendering project badges with services like
shields.io. It currently has a problem with dynamically chaning colours
but otherwise works. Implementation details and interaction with
shields.io are described in the docs.

api: add 'badges' endpoint to project object

---

squad/core/comparison.py
squad/core/notification.py
test/core/test_comparison.py

'fail'->'pass' changes are named 'progression' in SQUAD. The
TestComparison.progression property was introduced to provide means of
reporting such changes

core: detect changes from 'fail' to 'pass'

---

squad/ci/backend/lava.py

It might be a bug in LAVA but in some cases metadata for 'job' result is
empty. This causes exception when trying to retrieve 'error_type' from
metadata dictionary. This patch removes the exception and prevents
resubmission of such jobs.

ci: lava: fix case when LAVA fails to provide error_type

---

squad/api/rest.py
squad/core/notification.py
test/api/test_rest.py

The email rendering API now allows for selecting custom comparison
baseline. The keyword is 'baseline' and the value should be Build object
ID. In case when Build with given ID doesn't exist HTTP 500 is returned.
Builds from different projects can be compared.
Fixes #303

api: allow for baseline selection with build/<id>/email API

---

squad/frontend/views.py
test/frontend/test_basics.py

My motivation for having this is to be able to automate some performance
benchmarks against the build page, without needing to hardcode a build.

frontend: add shortcut to latest finished build

---

squad/core/models.py
test/core/test_build.py

Use case: 3 builds with 3 fast LAVA test jobs. Depending on the timing
of the builds, one or two builds will run and finish, the lava jobs will
finish, and notification will go out before the 3rd build has finished.
Build.finished would return without checking expected test runs when CI
(say, LAVA) jobs are involved.
Instead, we now return False (i.e. build is not finished) immediately if
there are any pending CI jobs, but if not, we still perform the checks
for the expected number of test runs for each environment.
The existing test case needed to be improved to create a more realistic
scenario, and a new test case for this use case has been added.

core: Build: check expected test runs even with CI jobs

---

squad/frontend/static/squad/compare.js
squad/frontend/templates/squad/compare.html

The dropdowns for each of the search fields are now removed on lost
focus in the input field.

frontend: hide dropdowns in comparetest page

---

squad/api/rest.py

Allow filter test jobs over it's relation to test runs. The filter can
now traverse to builds/project/groups to enable better filtering.

api: fix TestJobFilter to allow TestRun relation

---

squad/core/models.py
test/core/test_build.py

When collecting all test results by environment and KnownIssue is active
for one of the tests 'xfail' status appears in the dictionary. This
patch makes sure there is no missing key in that dict.
Fixes #341

core: add 'xfail' to default test statuses

---

squad/core/models.py

In notification emails tests are now stored in OrderedDict rather than a
dict. This makes sure they're reported in the same order as they were
collected.

frontend: Make order of tests important in notifications

---

squad/frontend/static/main.css
squad/frontend/templates/squad/_test_run_test.html
squad/frontend/templates/squad/build.html
squad/frontend/views.py

* xfail is now represented by the "bug" icon, and consistently colored
blue
* build page will now mark an environment with xfails, but without any
fails, in blue

frontend: improve presentation of known issues in the UI

---

squad/core/notification.py

This reuses the infrastructue that is already used to avoid duplicate
test results notifications.

core/notification: avoid duplicated "X FAILED TEST JOBS" notifications

---

.gitignore
squad/settings.py
test/test_architecture.py

This makes it easy to have local settings without having to export environment variables, or changing files that are tracked by git.

settings: optionally load squad/local_settings.py

---

squad/api/rest.py
test/api/test_rest.py

It was using the pagination settings, including field names etc from
TestRun to paginate Test's and Metric's.

api: fix pagination in TestRun detail routes

---

scripts/get-metrics
squad/core/comparison.py
squad/manage.py
test/api/test_rest.py
test/frontend/test_basics.py
test/performance.py
test/test_architecture.py

This pull request adds the infrastructure for recording the number of database
queries when executing a set of operations.
Initially queries are counted for frontend tests in
test/frontend/test_basics.py, and for the REST API test in
test/api/test_rest.py. This, however, does not need to be restricted to tests
involving web requests; in the future we can also record query counts for core
operations in isolation.
When executing tests via `./manage.py test`, the query counts are recorded in
JSON format into `tmp/queries.json`, and subsequent runs will check for
improvements and regressions. `tmp/queries.json` is also now read when
collecting metrics to be submitted to qa-reports.linaro.org, so we will de able
to track query counts over time.
The last commit fixes a performce regression in …

Collect and record number of database queries during tests

---

squad/frontend/templates/squad/test_history.html

On Chrome colspan doesn't work the same way as in Firefox. For this
reason tables in test history page were misaligned. This patch moves
known issue indicator inside the cell which fixes misalignment problem.
Fixes #366 

frontend: fix test history table for Chrome

---

squad/frontend/templates/squad/build.html

There was a reference to {{ test_run.job_id }} in a block that
didn't have `test_run` declared. Django just render it as blank.
The correct way here would be {{ status.test_run.job_id }}

frontend: Fix test_run's job_id on build page

---

squad/frontend/templates/squad/test_run_suite_metrics.html

I noticed the upper pagination passed 'metrics' to the include
while the lower pagination passed 'tests', which was probably
ctrl+v'ed from test_run_suite_tests.html

frontend: fix pagination iterator variable

---

squad/core/templates/squad/notification/diff.txt.jinja2
squad/frontend/templates/squad/_regressions_and_fixes.jinja2
squad/frontend/templates/squad/_test_run_test.jinja2

On Oct 31st there was an error in squad/frontend/templates/squad/_test_run_test.jinja2
where line 8 was still using `test.known_issues.all` instead of `.all()`. Probably because
the tests didn't cover the case where `test.has_known_issues` on line 7 evaluates to true.
I went ahead and found other places with missing that kind of fix

frontend: Fix missing changes in Jinja templates

---

doc/ci.rst
squad/ci/backend/lava.py
test/ci/backend/test_lava.py

is_pipeline field is long removed from TestJob object.
Remove obsolete checks in the code.

Clean up is_pipeline checks.

---

squad/api/ci.py

If program passes line 22, backend will not be None at least on line 28,
therefore `backend is None` will always be false.

api/ci.py: remove snippet that is always false

---

squad/api/rest.py

Test comparison API (project.test_compare) was incorrectly splitting the
test name in case suite name contains "/" character. This patch assumes
there are no forward slashes in the test name and fixes the problem.
Fixes #406 

api: fix test comparison results

---

doc/api.rst
requirements.txt
squad/api/rest.py
squad/api/urls.py

In order to support standard clients SQUAD offers an API schema that is
used to describe the interface endpoints.

api: add schema for REST API clients

---

squad/api/rest.py

Allow to filter TestJob objects based on almost all fields. Also add
possibility to filter on Project the TestJob belongs to.

api: add more filtering options to TestJob

---

doc/api.rst
squad/api/rest.py
test/api/test_rest.py

This patch adds 'force' option to 'report' API. Force has the same
effect as in case of 'email' api - it invalidates the cached object and
forces re-calculation.

api: add 'force' parameter to /build/<ID>/report

---

squad/api/rest.py
test/api/test_rest.py

By using HyperlinkedRelatedField instead of HyperlinkedIdentityField
baseline field points to the proper ProjectStatus object.

api: fix DelayedReport baseline to point to proper object

---

doc/api.rst
scripts/community_connector/main.js
scripts/community_connector/manifest.json

These two are minimal App Scripts to build a connector to SQUAD
data source.
This will take the input from the user asking for group, project
and token to display and it will do the rest.
User will be able to control environment visibility in runtime.
Fixes #359

Add community connector files for Google Data Studio data source.

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

Python yaml returns a None type object when the input string is empty

ci/backend/lava.py: fallback project_settings

---

doc/ci.rst
doc/conf.py
doc/index.rst
doc/install.rst
doc/intro.rst
doc/lava_usecase.rst
doc/quickstart.rst

It closes #441 and also:
- fixes small typos
- changes `team` for `group`
- fixes processes table
- adds documentation to install libyaml-dev before installing SQUAD dependencies

docs: add step-by-step on how to set up SQUAD with LAVA

---

squad/core/notification.py
squad/core/templatetags/squad_notification.py
squad/jinja2.py
test/core/test_notification.py

By default Django/Jinja2 escapes some caracters, e.g. ' and & to html
entities. That troubles subject content and text emails with escaped characters.
Now the behavior works as follows:
1. if template comes from string: do not escape
2. if template comes from a file and filename endswith ```.txt.jinja2```: do not escape
3. else: escape

core/notification.py: turn off escaping for text emails

---

squad/core/management/commands/update_project_statuses.py
test/core/test_update_project_statuses.py

A bug #432 was introduced which broke fixes and regressions db field
entries. This management command updates the project statuses.
It assumes that the code fix is in the code base.

Add management command to update project statues from scratch.

---

squad/core/management/commands/update_project_statuses.py

We should not use plain print(); they pollute the test output as follows:
......[...].....Progress: 100%[##########].
......[...]
With this change, the progress will be displayed by a proper logging statement,
at every 100 items.

update_project_statuses: avoid cluttering test output

---

squad/core/comparison.py
squad/core/models.py
test/performance.py

These commits reduce a lot the RAM consumption when receiving new test results.
The main culprit is the TestComparison class, which used to load every single
test object to RAM at once. That just does not work with hundreds of thousands
of tests.

reduce RAM usage when processing new test results

---

squad/core/models.py
squad/frontend/templates/squad/_project_list.jinja2
squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templates/squad/group.jinja2
squad/frontend/templates/squad/index.jinja2
squad/frontend/templates/squad/project-nav.jinja2
squad/frontend/templates/squad/test_history.jinja2
squad/frontend/templates/squad/test_run.jinja2
squad/frontend/templates/squad/test_run_suite_metrics.jinja2
squad/frontend/templates/squad/test_run_suite_tests.jinja2
squad/frontend/templates/squad/user_settings/subscriptions.jinja2

The field name is optional for both group and project created through
the API or via the command line. But groups and projects with empty
names are displayed as `None` throughout the UI.
This patches changes all instances of `group.name` and `project.name` to
use a new `display_name` property, which will fallback to the slug in
case the name is empty.

frontend: support groups and project with empty name

---

squad/settings.py

This avoids waiting forever when a connection to RabbitMQ cannot be
established.
Fixes #478

celery: set maximum number of producer connection attempts

---

squad/container_settings.py

After running tests locally, I got a pep8 error:
squad/container_settings.py:25:1: E402 module level import not at top of file
Weirdly, this is not being flagged by travis. Running flake8:
3.2.1 (pycodestyle: 2.2.0, mccabe: 0.5.3, pyflakes: 1.3.0) CPython 3.5.3 on Linux

fix pep8 E402 module level import not at top of file

---

squad/core/models.py
test/core/test_group.py

Group access was defined by access to Project objects. So if there were
no projects defined even suepruser didn't have access to group objects
from API. With this patch users have access to Groups that are connected
to their user group and Groups that contain public projects.

core: allow superuser access to all groups

---

squad/core/models.py
squad/frontend/templates/squad/base.jinja2
test/core/test_group.py
test/frontend/test_basics.py

We need to go through the accessible projects to be able to count how
many projects in each group are accessible to each user. i.e. if a group
has one public and one private project, an anonymous user should see it
as having only one project.

core: GroupManager.accessible_to: restore and fix project count

---

squad/frontend/static/main.css
squad/frontend/static/squad/common.js
squad/frontend/templates/squad/_regressions_and_fixes.jinja2

Leave popover hanging so user can select and copy-paste the
text within. The popover will close on next click on the
regression/fixes button.

frontend: regressions and fixes need to be in copy-pastable

---

squad/ci/tasks.py
squad/core/models.py
squad/core/notification.py
squad/mail.py
test/test_mail.py

This is to avoid people's vacation autoresponders replying to squad
mail.
References:
- https://tools.ietf.org/search/rfc3834
- http://www.redmine.org/projects/redmine/repository/revisions/2655/
- https://blog.returnpath.com/precedence/
- X-Auto-Response-Suppress is used by github

mail: add bulk mail headers to outgoing mail

---

squad/api/data.py
squad/core/queries.py

Previously we passed date_start and date_end as strings to
get_metric_data which was incorrect because make_aware expects
datetime objects and not strings. This patch fixes that.

Fix api/data call date arguments.

---

squad/core/models.py
squad/frontend/static/squad/build.js
squad/frontend/static/squad/controllers/buildSettings.js
squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templates/squad/build_settings.jinja2
squad/frontend/urls.py
squad/frontend/views.py
test/unit/test_buildSettings.js

Add build settings as a new tab in `build-nav.jinja2`, thus
allowing end-user to mark whether or not that build should
keep its data in an event of Data Policy Rentention removal.
This will avoid the need of going in admin UI to do the same action,
also usefull for future build-specific settings.

Add build settings tab

---

squad/ci/backend/lava.py

This avoids having several test results called "boot/${device_type}".
each boot will be named "boot-${job_name}/${device_type}"

ci/lava: compose boot test identifier from job_name

---

Dockerfile

Having the installation of packages after WORKDIR and COPY forces a
reinstallation of the dependencies every time there is any change to the source
tree. By installing the dependencies directly on top of the base image, that
layer will be used from the cache and only needs to be rebuilt if the list of
deopendencies change.
The resulting image has a couple of extra layers, but is the same size as
before:
squad/after   latest   3e6bc1fd3f33  6 seconds ago   280MB
squad/before  latest   e09e3b1ead22  2 minutes ago   280MB
(Also, install iproute2 together with auto-apt-proxy so that the later works properly)

Dockerfile: cache installed dependencies

---

scripts/test-docker

We want the docker image to use packages from Debian. requirements.txt
should not require anything that is not available in the target Debian
release.

test-docker: fail on locally-installed Python packages

---

squad/frontend/templates/squad/build-nav.jinja2

@terceiro right after I merged your build-settings branch, I realized that Group and Project settings tab are named "Group settings" and "Project settings", respectively. So this is just a minor tweak to the build settings tab name.

Standardize "settings" tab to be similar to Group and Project 

---

squad/frontend/templates/squad/_builds_table.jinja2
squad/frontend/templates/squad/_project_list.jinja2
squad/frontend/templates/squad/_test_results_summary.jinja2
squad/frontend/templates/squad/build.jinja2
squad/frontend/templates/squad/test_run.jinja2

This fixes the absence of xfail in a couple of pages, and will make it
easier to translate those bits of UI.

frontend: extract "test results summary" into a shared template

---

squad/api/rest.py
squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/models.py
squad/core/models.py
test/api/test_rest.py
test/ci/test_models.py
test/core/test_project_status.py
test/core/test_tasks.py

PyYAML has deprecated the default `yaml.load`. It recommends explicitly specify
the loader or calling a shortcut function, which is done in this commit.
Source: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

fix yaml.load default Loader warning

---

squad/frontend/templates/squad/group-nav.jinja2

The "Projects" tab allows users to navigate from project settings and creating new projects. If the user does not have such privileges, there will be only one tab pointing to the current page, making no use
for it.

Show "Projects" tab only if user had specific permission

---

doc/api.rst
squad/api/rest.py
test/api/test_rest.py

Creates subscribe/unsubscribe endpoints for /api/projects/<id>/. These are used to create/remove email subscriptions.

Subscribe api

---

squad/frontend/comparison.py
squad/frontend/templates/squad/_pagination.jinja2
squad/frontend/templates/squad/_test_results_table.jinja2
squad/frontend/templates/squad/compare_projects.jinja2
squad/frontend/templatetags/squad.py
test/frontend/test_template_tags.py

While that didn't reduce time consumed in generating the comparison, now it feels way faster just because of much fewer html rendering.

compare_projects.jinja2: add pagination to test results

---

squad/frontend/static/squad/controllers/charts.js

In current chart is quite tricky to get a tooltip to show up.
You need to hover on the specific point to get it displayed, and
that's just a few pixels wide.
With this configuration set up, a tooltip will be displayed
pointing to the nearest point that the mouse is hovering on.
Also, if two points overlap each other, the tooltip will
include both of their data.

squad/controllers/charts.js: display tooltip on line hover

---

squad/api/rest.py

This patch allows to filter tests using KnownIssue objects and it's
filter. It also allows to construct more complex queries for KnownIssue
objects themselves.

api/rest: Add KnonwIssue filtering to Test object

---

squad/frontend/static/squad/controllers/compare.js

So far the minimum input required in search boxes in test comparison
page was 1 character. This led to situation where it was hard to use the
form without knowning at least 1st character of the suite or test name.
This patch removes the 1 character limitation and allows for empty
searches.

frontend: allow empty searches in test comparison page

---

squad/core/locale/pt_BR/LC_MESSAGES/django.po
squad/frontend/locale/pt_BR/LC_MESSAGES/django.po

Done translating to Brazilian portuguese. @terceiro could you double check it briefly? Some words are just too tricky to translate.
Also, I spotted a small typo ("projec" instead of "project') in [delete.jinja2](https://github.com/Linaro/squad/blob/master/squad/frontend/templates/squad/project_settings/delete.jinja2#L15). When I ran `./scripts/update-translation-files`, both polish and portuguese as well as *pot files got changed. Maybe we should add that step to the documentation as well.

Brazilian portuguese translation for SQUAD UI

---

squad/api/ci.py
squad/http.py
test/api/test_ci.py

This patch adds support for token authentication in /api/resubmit/<id>.
This API will now work with external requests and Auth-Token header.
Header value should be set to the token used with REST API.

api: fix authentication in resubmit API

---

doc/ci.rst
squad/ci/backend/lava.py
test/ci/backend/test_lava.py

LAVA results always carry 'pass/fail' information. So far this was
discarded in case there was measurement associated with the result. This
patch allows to save LAVA result as both Test and Measurement.
Fixes: #536

ci: allow cloning LAVA results with measurements

---

doc/ci.rst
squad/ci/backend/fake.py
squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/models.py
test/api/test_ci.py
test/ci/backend/test_fake.py
test/ci/backend/test_lava.py
test/ci/test_models.py
test/core/test_build.py
test/frontend/test_test_job.py
test/integration/test_build_notification_from_ci.py

This patch adds support for multinode jobs. In case of multnode LAVA API
calls return list in the following form: [job_id.0, job_id.1, ...].
SQUAD will use each of the IDs in the list to create new TestJob object.
This way we ensure that results from all test jobs are assigned to
proper build and fetched.

ci: add support for LAVA multinode jobs

---

squad/frontend/templatetags/squad.py
test/frontend/test_template_tags.py

Fix a bug where every page change, the variable `page` is appended
to the querystring, instead of being updated.
For some reason, `query_string.update` was appending `page` key in every iteraction.

frontend/templatetags: fix pagination get_page_url

---

.ackrc
.ctags
.gitignore
squad/frontend/static/download.conf
squad/frontend/templates/squad/_test_results_table.jinja2
squad/frontend/templates/squad/base.jinja2
squad/frontend/templates/squad/build.jinja2

I noticed that the plugin `floatThead` as in *float table head*, was named wrong in download scripts as `floatThread`. This PR renames floatThread to floatThead and add `thead` where needed.
Hopefully it won't conflict with https://github.com/Linaro/squad/pull/543, but if it does, I'll update this PR.

frontend: fix floatThead

---

doc/ci.rst
squad/ci/backend/lava.py
test/ci/backend/test_lava.py

This allows specific projects to avoid parsing `auto-login-action` as boot results

Ignore lava boot

---

squad/frontend/static/download.conf

CVE-2019-10744 reported a vulnerability in lodash < 4.17.13
that was fixed in that version
See https://github.com/lodash/lodash/pull/4336 for context.

frontend: js: update lodash to 4.17.14

---

squad/frontend/static/main.css

Fix word-wrap for long metric names and for long test names
when displaying regressions/fixes
From this
To this

frontend: css: fix word-wrap

---

squad/frontend/templates/squad/project_settings/base.jinja2

The template already puts a » in the correct place, so there is no need
to include one in the title itself.

frontend: fix page title in project settings

---

squad/ci/backend/lava.py
test/ci/backend/example-broken-log.yaml
test/ci/backend/test_lava.py

In case LAVA logs are malformed or LAVA returns 404 (Canceled jobs)
backend exits gracefully and logs are ignored.

ci: improve parsing of LAVA logs

---

squad/frontend/templates/squad/_results_table.jinja2

Forgot to restrict the "mean stddev" details only to be displayed for metric comparison.

frontend: results_table: show "mean (stddev)" details only for metric comparison

---

squad/api/rest.py
squad/frontend/comparison.py
squad/frontend/static/compare.css
squad/frontend/static/squad/controllers/project_compare.js
squad/frontend/static/squad/project_compare.js
squad/frontend/templates/squad/compare_projects.jinja2
squad/frontend/templatetags/squad.py
test/frontend/test_comparison.py

Closes https://github.com/Linaro/squad/issues/186
This PR includes the following improvements:
- restrict project comparison to projects from the same group only
- change group by typing its name or slug under "Group" header
- by selecting a project, a dropdown box appears next to it for build selection
- by default, the latest build is selected
- change build by typing its version string

Improve project compare

---

Dockerfile
scripts/test-docker

This ensures that the final docker image will contain only Debian
packages.

Dockerfile: don't install packages from pip

---

squad/core/comparison.py
squad/frontend/comparison.py
squad/frontend/static/compare.css
squad/frontend/static/squad/controllers/project_compare.js
squad/frontend/templates/squad/_results_table.jinja2
squad/frontend/templates/squad/_results_transitions_filter.jinja2
squad/frontend/templates/squad/compare_builds.jinja2
squad/frontend/templates/squad/compare_projects.jinja2
squad/frontend/templatetags/squad.py
test/core/test_test_comparison.py
test/frontend/test_comparison.py
test/frontend/test_template_tags.py

Closes https://github.com/Linaro/squad/issues/566
Add a transitions table that allow users to select which transitions from a comparison to be shown.
- All tests that have exact same results along builds and environments are **not** shown
- By default only *pass-to-fail* and *fail-to-pass* transitions are shown
- If a test has at least one differing result, all its results across builds & envs are displayed
- If the transitions selected didn't pick up any change in a specific environment, that column will **not** be displayed
- If no transitions are selected, the frontend will automatically go back to default (*pass-to-fail* and *fail-to-pass*)
- As boxes are checked/unchecked, the frontend will be updated accordingly
- Check "ignore all transitions" box to go back to regular comparison …

frontend: filter comparison by transitions

---

squad/frontend/templates/squad/test_history.jinja2
squad/frontend/templatetags/squad.py
test/frontend/test_template_tags.py

Example: https://qa-reports.linaro.org/lkft/linux-next-oe/tests/kselftest/binderfs_binderfs_test
When clicking on the "i" icon, a modal window is expected to pop up. Instead, it was triggering an exception:
`Uncaught SyntaxError: Unexpected token d in JSON at position 45`
Also, this fixes: [LSS-145](https://projects.linaro.org/browse/LSS-145)

Fix broken JS on test history page

---

squad/api/ci.py
squad/ci/models.py
test/api/test_ci.py
test/api/twoline_definition.yaml

Fix the encoding for a testjob's definition when it is provided as an uploaded file.
This was reported at https://lists.linaro.org/pipermail/squad-dev/2019-September/000183.html

api: ci: fix definition file encoding

---

squad/core/utils.py
test/core/test_project.py

This is insecure, and deprecated.

yaml_validator: drop usage of simple yaml.load

---

squad/api/rest.py
squad/api/utils.py
test/api/test_rest.py

Add subclass of rest_frameworks.pagination.CursorPagination in order to enable `page_size_query_param`, allowing custom page sizes.
NOTE: by default, limit can be no greater than 1000. If that limit is to be increased, consider overriding `max_page_size`.

api: utils: add CursorPaginationWithPageSize

---

squad/ci/backend/lava.py

This fixes a severe performance problem when converting large log files.

ci: lava: speed up conversion of YAML of logs to pain text

---

squad/ci/backend/lava.py

This is probably less of a problem than __parse_log__() but still it's
more efficient to do it this way.

ci/lava: replace concatenation with StringIO

---

requirements.txt

Fixes /api/schema/ 
Django RestFramework was crashing when schema_view was being invoked, that was due to an old version of pyyaml (3.12) that did not support "sort_keys" for "dump_all".
ref: https://github.com/yaml/pyyaml/commit/07c88c6c1bee51439a00bc07827980fbb161a1ad#diff-2cf6b2c84206cb7fde75192c9a8e2a19R277

requirements.txt: fix minimal version for pyyaml

---

doc/install.rst
squad/settings.py

This change allows to create multiple celery workers, each dedicated to
specific queues. Some tasks are slower than the other and moving them so
separate queues helps reducing congestions.

settings: split tasks to separate queues

---

squad/run/worker.py

When no concurrency is specified, celery starts one worker thread for
each CPU thread available (i.e. `nproc`).
In a production environment, one most likely wants to utilize as much
processing as possible, so requiring an explicit parameter for that is
silly. For the cases where fine tuning is necessary, it's still
possible.
In development environments, running with a single worker thread
prevents one from hitting concurrency issues that might come up in
production.

worker: don't constrain concurrency by default

---

squad/api/rest.py
squad/api/utils.py
squad/core/models.py
squad/settings.py

This PR does several things:
* remove duplicate call to DjangoFilterBackend in settings (this caused a huge drag on the api, more details in this commit https://github.com/Linaro/squad/commit/cbea9f44acdf9da3842eb931f5836dd290a736af )
* disable API POST forms completely
* in TestRunFilter, use Build's queryset without ordering (query runs much faster)
* avoid passing a query like `SELECT id FROM core_project` when user is admin or staff (they already have permission to see everything anyways)
* exclude "metadata" from TestSerializer
* prefetch "suite" and "known_issues" in TestViewSet
* prefetch "environments" in KnownIssuesViewSet
After these changes, I noticed a huge improvement in snappiness of the API. 
Running ` time wget 'http://localhost:8000/api/tests/?test_run__build__project__slu …

Improve test api performace

---

squad/core/comparison.py
squad/core/models.py

This improves the overall performance of ProjectStatus.create_or_update. The two main bottlenecks where in TestSummary and TestComparison, consuming a lot of memory and making thousands of queries to db, respectively. I've managed to perform some heavy tasks in db.
In my local database (October last year's dump from production) I got some benchmarks that reduced the time in half using this [patch](https://pastebin.linaro.org/view/20455d97) compared to [master](https://pastebin.linaro.org/view/5416423a). Maybe you guys can help out just to be sure it'll improve performance overall.

Improve fetch performance

---

squad/core/tasks/__init__.py
test/core/test_tasks.py

Ignore tests and metrics that have names longer than 256 characters. We should consider increasing the max length of the name field in the future though.
This avoids getting an exception: DataError value too long for type character varying(256)

core: tasks: ReceiveTestRunData: ignore tests and metrics with long names

---

squad/core/comparison.py
squad/core/models.py
test/core/test_project_status.py

This PR reverts calculating fixes and regressions only at the end of the build, and it changes TestComparison to filter tests by testrun ids

Faster comparison

---

squad/core/comparison.py
squad/core/utils.py
test/core/test_utils.py

After https://github.com/Linaro/squad/pull/620, staging DB just took forever to calculate TestComparison for builds with over 1000 testruns. Postgres queries were taking an insane amount of time to return (10+ hours). This patch fetch tests using batch of 400 test runs ids at a time. I've run a few queries in staging and production and this number seems to be the sweet spot.

Test comparison

---

squad/core/comparison.py

Remove the use of iterator. This causes postgres to increase number of locks some how.

core: comparison: remove the use of iterator over tests

---

squad/core/comparison.py
squad/core/models.py
squad/core/notification.py
squad/core/utils.py
test/core/test_build_summary.py
test/core/test_project_status.py
test/core/test_test_comparison.py
test/core/test_test_summary.py
test/core/test_utils.py

This PR changes several snippets in the code, trying to minimize the number of trips to db, applying less load on it too:
1. Re-adjust [chunk size](https://github.com/Linaro/squad/blob/master/squad/core/comparison.py#L190) from 400 to 100. In a single threaded architecture (dev), 400 testrun-ids at a time proved to be the sweet spot, but on a multi-threaded one (staging and production), having multiple calls to that snippet makes things slow again.
2. Prefetch known_issues from failing tests. If a testrun contains 1000 tests with known_issues, this would result on 1000 extra queries in the DB. I just moved them to a separate method to be called after tests are processed
3. Simplify calculations for TestSummary using States instead of summing test-by-test. I also added what @terceiro asked …

Reduce number of queries

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

Addresses https://github.com/Linaro/squad/issues/624 and removes workaround added in 50f694d965e5e19e46ae667ce99ff2e884c8d707

ci: lava: fetch jobs right away

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

This prevents the whole fetch from breaking due to a single bad character in a test log. Ex:
```
[2019-10-31 13:22:53,972: INFO/ForkPoolWorker-1] squad.ci.tasks.fetch[21d67bd5-6032-4195-8d31-5f012bbe3382]: fetching validation.linaro.org/1920041
[2019-10-31 13:25:41 +0000] [ERROR] Task squad.ci.tasks.fetch[21d67bd5-6032-4195-8d31-5f012bbe3382] raised unexpected: UnicodeDecodeError('utf-8', b'AYd\xb19R\xa3\xf7\xb8K\xbfw\xb9\x08\xd5/+\xd9>t_\xcdU\xcb\xd3\xd3\xfb\xa5=p=\xff\xe4l$?\x94\x12~\xcdyV\xd6\x0e\x95S\xdeFNp\x83%\x04\x1c\x00P\x9bs=d"\xe3\x93\xcb!D\xc1t2\xd0\x8d\xd8\x1c\x89)\x943g\xcc\x1e\x85\x05?\xd1 "X\x99\xe5;\x17\xc95fnq/\x18\xdb\x17\\b\xc2\xa2,\xec\x95\x9a\x15\xde\x03I\xb8\x10\x1a\x9b\x86gQW\\i\x18Qo\xd6\xecj\xe5\x16R]\x97f\xc8ZjQ\xa45\x07\xe0\x88\xde\x9a)x\xcc\xc1:\xba\x9b\xb2Xi+\x …
```

ci: lava: handle unicode errors gracefully

---

Dockerfile
scripts/test-docker
setup.py

The version constraints in requirements.txt are needed when installing
from pypi, but when installing from Debian packages we can just trust
what's in the repository since we do run the tests against that.
The issue manifests when you call the installed commands (e.g.
squad-admin), but not when you call ./manage.py. So, also add an
explicit call to squad-admin to scripts/test-docker so we know if we
introduce a regression.

Dockerfile: ignore version constraints from requirements.txt

---

squad/frontend/queries.py

From https://projects.linaro.org/browse/LSS-1059
> The loading time for the main art-metrics page is around 5-10s:
> https://qa-reports.linaro.org/art/master-baseline/metrics/
> 
> I was wondering if some things could be optimized to load faster, or show a progress bar.
> Due to varying server load, this can sometimes be up to 15 seconds.
This happens because querying the metric names was a bit too slow. I changed it so it uses similar strategy when querying tests using testrun ids. It improved locally.

frontend: reduce query time fetching metric names

---

squad/core/history.py
test/core/test_history.py

This fixes hitting a situation like 
```
AttributeError at /lkft/linux-next-oe/build/next-20191024/tests/
'NoneType' object has no attribute 'description'
```
due to tests created in a way that do not have associated metadata (in plugins)

core: test_history: handle tests with no metadata

---

squad/plugins/linux_log_parser.py
test/plugins/linux_log_parser/multiple_issues_dmesg.log
test/plugins/linux_log_parser/rcu_warning.log
test/plugins/test_linux_log_parser.py
test/plugins/test_plugin.py

Closes https://github.com/Linaro/squad/issues/592 and https://github.com/Linaro/squadplugins/issues/3. This PR has been moved from https://github.com/Linaro/squadplugins/pull/13
I managed to put several regex'es together so that findall is called only once. Not sure if that has better performance than running each regex on its own. Also, there's a pre-regex that filters-out all non-kernel messages (that don't start with [number.number]), thus reducing log size considerably (specially in jobs with lots of target output).
By default, there are 6 tests, each represented by a regex, all under kernel-issues suite:
if a test has no match, result=True
if a test has at least one match, result=False
if a test matches more than once, all occurrences are concatenated and saved to its log. Meaning …

plugins: linux_log_parser: improve kernel log parsing

---

squad/settings.py

This will turn `DEBUG` only when `ENV` is not production or staging.
`ENV` was hard coded to "production" in both production and staging deployments: https://github.com/Linaro/qa-reports.linaro.org/blob/master/ansible/roles/squad/templates/environment#L13
I fixed that in the PR https://github.com/Linaro/qa-reports.linaro.org/commit/2f2cf904c022afae557e63754d1db242bf27b220#diff-818648361d20d54acf2e16ac713065d7R14 so that it is set to their correct environment accordingly.

settings: turn on debug only when needed

---

doc/install.rst
squad/settings.py

This allows celery to create queues with user defined prefix names
ref: http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html#queue-prefix

settings: add support to prefix-named queues

---

.coveragerc
.dockerignore
.gitignore
.travis.yml
pytest.ini
requirements-dev.txt

Our current coverage is almost 79%, so we will fail tests if it goes
under 78. With time we want to increase that threashold as high as
feasible.
It would be nice to switch to pytest completely at some point, but there
are more changes needed for that to happen

Add coverage testing with pytest

---

squad/api/rest.py
test/api/test_rest.py

Enabled filtering on created date for builds in rest api. This will be required for pulling specific builds from the client side reporting tool.

Enabled filtering on created_at date for builds in api

---

squad/api/rest.py
test/api/test_rest.py

Enable filter testruns by 'completed' status. This is required to filter only meaningful testruns for downstream report processing.

api: rest.py: enable filtering testruns by 'completed'

---

squad/frontend/project_settings.py
squad/frontend/templates/squad/project_settings/advanced.jinja2
squad/frontend/templates/squad/project_settings/base.jinja2

This will allow project admins to edit `project_settings` field in the self service menu, without having to go to Django admin page

frontend: project_settings: add advanced settings tab

---

squad/core/admin.py

This one-liner will allow users to duplicate projects with a "Save As New" option (asked by @danrue):
It'll go from that:
to this:
Ref: https://stackoverflow.com/questions/180809/in-the-django-admin-interface-is-there-a-way-to-duplicate-an-item

core: admin: enable `save as new` option for projects

---

squad/ci/tasks.py
test/ci/test_tasks.py

Because of the lab outage this morning, failed attempts to `submit` tasks are kept in the workers to be retried in one hour, which is the exact time for SQS to re-queue them (due to visibility timeout is also 1 hour). Several tasks got picked by multiple workers, thus submitting exact same tasks multiple times to labs.
This PR makes sure to not submit tasks if the testjob has already been submitted.

ci: tasks: avoid multiple submissions

---

squad/frontend/static/main.css
squad/frontend/templates/squad/_test_results_envbox.jinja2
squad/frontend/templates/squad/_test_results_suitebox.jinja2
squad/frontend/templates/squad/_test_results_table.jinja2
squad/frontend/templates/squad/build.jinja2
squad/frontend/views.py

This was asked by @danrue and @mwasilew when the number of environments is too big (I'm assuming a number > 8) viewing suites in the build view gets hard.
I added an option so that the user can toggle the layout to this one below:
Clicking '+' a table like the one below is shown:
**NOTE 1** for builds with number of environments less than 8, the default behavior won't change. If that's more than 8, the 'box' view will kick in, but users can still click on the table layout to have the old style back. The opposite is valid, meaning if a build has less than 8 environments, users can simply click on 'box' view.
**NOTE 2** as requested by @danrue and @mrchapp , environments are now sorted in alphabetical order.

Allow users to switch test results table layout

---

squad/celery.py

If task-A has an ETA of 10 minutes gets picked by a worker, a given task-B with an ETA of 1 minute wouldn't be delivered to any worker because of the FIFO strategy. Only after 10 minutes, task-B would've been delivered to workers.
To prevent that behavior, the SQS documentation [1] says that the `MessageGroupId` should be set to different values. This attribute is used in case where tasks order are crucial, but that's not the case of SQUAD when processing notifications.                                                                                                                                                                                   
ref:
[1] https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagegroupid-property.html

core: tasks: notification: handle ETA in notification_timeout

---

squad/frontend/templates/squad/_test_results_envbox.jinja2
squad/frontend/templates/squad/_test_results_suitebox.jinja2
squad/frontend/templates/squad/build.jinja2
squad/frontend/templatetags/squad.py
squad/frontend/views.py
test/frontend/test_template_tags.py

Closes https://github.com/Linaro/squad/issues/655
This will display only failures by in the test results table of the build view. Also, it'll render all boxes opened by default, allowing users to toggle it afterwards if needed.

Show failed suites first

---

squad/ci/tasks.py
test/ci/test_tasks.py

If a test job submission fails, the error message is saved in `failure` attribute. But in a successful retry afterwards, the failure message was still going to show up.
This PR clears `failure` whenever a test job submission was successful.
Also, I changed the criteria do display the successful and error icons in the test job page. People would get confused to see the image below:
The two test jobs at the bottom had their submission failed in the first attempt, but they were successful later on, but the error icon would still be displayed, which is confusing.

Clear testjob failure

---

requirements.txt

This will prevent Django 3.0 from being installed thus prevent our builds in travis from failing

requirements.txt: top off django version

---

squad/core/models.py
test/core/test_build.py

This PR makes builds finish earlier by ignoring `expected_test_runs` when set to None or 0 (zero)

core: models: finish builds status earlier

---

doc/ci.rst
doc/intro.rst
doc/lava_usecase.rst
doc/plugins.rst
squad/core/tasks/__init__.py
test/core/test_tasks.py

This PR adds an example of submitting test results through the api using Python's requests library. Also, it fixes a bug that happened when a float value was passed as job_id.
Closes #656

Add submit test results example with results

---

squad/api/views.py
squad/ci/models.py
squad/core/tasks/__init__.py
squad/core/tasks/exceptions.py
test/ci/test_models.py

Add DuplicatedTestJob exception to handle cases where a testjob is being submitted twice. Before this patch, we were considering that case as `InvalidMetadata`.

ci: models: backend: handle duplicated testjob as new exception

---

scripts/upload

This just removes a leftover folder `squad.egg-info`, it's already being removed before release anyways: https://github.com/Linaro/squad/blob/master/scripts/release#L54

scripts/upload: remove build leftover files

---

squad/core/notification.py
test/core/test_notification.py

This morning we got an error saying that one email got too big (>10MB) and wasn't able to deliver to recipients.
This patch checks if email content is >1MB and send a link to a build's email directly from the api. This email is a DelayedReport, and will be deleted in 1 day after its creation.

Avoid sending emails when body >1MB

---

squad/core/migrations/0126_metricthreshold_environment.py
squad/core/models.py

This is to fix unique together constraint in MetricThreshold model. Env should replace project to avoid duplicate ids when inserting two envs for a project.

core: models fix metricthreshold unqiue contraint

---

doc/intro.rst

Fix a line break that prevented python example from being rendered in docs

doc: fix python example for submissions

---

doc/api.rst
squad/frontend/urls.py
squad/frontend/views.py
test/frontend/test_basics.py

The concept of project badge was extended to build. With this commit
each build can produce a badge that can be included in your build
system.

frontend: add badge for build

---

squad/core/tasks/__init__.py
test/api/tests.py

This kinda undo this commit: https://github.com/Linaro/squad/commit/8a4ef7edb00916a49dcbec6dbbf83f1ccd1e2fb4
"job_id" is mandatory only if metadata is present in submission, but if no metadata is passed, then it's generated. I'm making it optional even if it's passed in metadata. Duplicate check still happens when job_id is present in metadata though

core: tasks: make "job_id" optional

---

squad/plugins/linux_log_parser.py
test/plugins/test_linux_log_parser.py
test/plugins/test_plugin.py

Run linux-log-parser plugin for testrun, instead of testjob. This will run the plugin even for results submitted via the api.
Screenshots available here: https://github.com/Linaro/squad/issues/658

plugins: linux_log_parser: run plugin for testruns

---

Dockerfile
requirements-dev.txt
requirements.txt
squad/api/rest.py
squad/compat.py
test/api/test_rest.py

core: api: add tests status totals to testrun endpoint to be readily
available for client calls.

Add tests status summary to Testrun api

---

squad/core/history.py
test/frontend/test_history.py

Fix this error:
```
AttributeError at /lkft/linux-stable-rc-5.5-oe/tests/linux-log-parser/check-kernel-warning-1360505
'NoneType' object has no attribute 'instructions_to_reproduce'
```

core: history: check for empty suite metadata

---

squad/plugins/linux_log_parser.py
test/plugins/test_linux_log_parser.py

Fix this error:
```
Plugin postprocessing error: expected string or bytes-like object
Traceback (most recent call last):
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 259, in __call__
self.__call_plugin__(plugin, testrun)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/core/tasks/__init__.py", line 264, in __call_plugin__
plugin.postprocess_testrun(testrun)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/plugins/linux_log_parser.py", line 65, in postprocess_testrun
log = self.__kernel_msgs_only(testrun.log_file)
File "/srv/qa-reports.linaro.org/lib/python3.5/site-packages/squad/plugins/linux_log_parser.py", line 34, in __kernel_msgs_only
kernel_msgs = re.findall(r'^\[[ \d]+\.[ \d]+\] .*?$', log, re.S …
```

plugins: linux_log_parser: ignore empty logs

---

squad/core/tasks/__init__.py
test/api/tests.py

I introduced this bug back when made job_id optional. Now it's fixed for real

core: tasks: fix job_id as integer

---

squad/api/rest.py
test/api/test_rest.py

For every call to `/api/builds/id/report/?force=true` a new report will be created.
Close https://github.com/Linaro/squad/issues/503

api: rest: fix force-created reports

---

squad/ci/management/commands/testfetch.py
squad/ci/models.py
squad/ci/tasks.py
test/ci/backend/test_lava.py
test/ci/test_models.py
test/ci/test_tasks.py
test/core/test_build.py
test/integration/test_build_notification_from_ci.py

Close https://github.com/Linaro/squad/issues/674
This PR is separated in two commits:
* first merges `Backend.really_fetch` into `Backend.fetch` so that we can query a TestJob, fetch it and mark it as fetched or not. Also, it brings a check for `maximum_number_of_attempts` to within fetch as well.
* second wraps the block that query - check - update TestJob with a `transaction.atomic` statement along with `select_for_update()` to prevent race condition.

Fix fetch race condition

---

.travis.yml
squad/ci/models.py

In case the job is still in the queue or is in progress, fetch() raises
TemporaryFetchIssue from within block that catches FetchIssue. Since
TemporaryFetchIssue derives from FetchIssue, the exception is
immediately consumed and fetch_attempts counter is increased. This leads
to maxing out fetch_counter for jobs that stay in the queue for a long
time. This patch removes the exception and instead returns from the
fetch() function without an error. This doesn't result in increasing
fetch_attempt counter.

ci: fix Backend.fetch() implementation

---

doc/ci.rst
squad/ci/backend/lava.py
test/ci/backend/test_lava.py

If LAVA job fails with infrastructure error but before that produces
valid results, these results can be pulled to SQUAD. It is possible
using CI_LAVA_IGNORE_INFRA_ERRORS flag. It can be set in either backend
or a project.

ci: lava: add flag allowing to accept results from failed jobs

---

squad/api/rest.py
squad/ci/models.py
test/api/test_rest.py
test/ci/test_models.py

When test job is not yet submitted cancel() marks it as submitted and
fetched and sets failure message.

ci: improve TestJob.cancel()

---

squad/frontend/templates/squad/build.jinja2

When users change the layout type in build page, "failures only" checkbox would always reset to checked. This patch preserves its value as users toggle between layout types

frontend: build: fix missing "failures only" filter

---

squad/frontend/comparison.py
squad/frontend/templatetags/squad.py
test/frontend/test_template_tags.py

There was a bug tha caused 500 errors when new transitions were selected. This was due to how we update querystring parameteres. This patch fixes that.

frontend: comparison: fix transitions

---

squad/frontend/templates/squad/tests.jinja2
squad/frontend/templatetags/squad.py
squad/frontend/views.py

When test name contains / it's now converted on the fly to $ to make
regexes work properly. Down side is that $ can't be used in the test
names any more. This should be mentioned in the docs.

frontend: fix URL reverse for test names with /

---

squad/core/models.py
squad/frontend/templates/squad/_builds_table.jinja2
squad/frontend/templates/squad/builds.jinja2
squad/frontend/templates/squad/project.jinja2
squad/frontend/views.py

This reduces a few queries in project and builds pages:
before:
project home page: 15 queries take ~90ms, page takes ~500ms
builds page: 14 queries takes ~10ms, page takes ~300ms
after
project home page: 8 queries take ~8ms, page takes ~200ms, about 50% faster
builds page: 12 queries takes ~8ms, page takes ~250ms, about 30% faster

Improve load times for project and builds page

---

squad/admin.py
squad/ci/admin.py
squad/core/admin.py

The fix consists in not loading a list of objects to be deleted when Build gets deleted. Some builds have thousands of TestRuns with thousands of tests attached. Loading a list of objects is just not practical.

Fix timeout when deleting builds

---

squad/api/rest.py
squad/frontend/static/squad/controllers/compare.js
test/api/test_rest.py

OK This time I took a bit more time reading the code and removing unnecessary queries. Another change in this patch is that instead of sending parallel ajax requests to the backend, it's done one-by-one.
Sending all in parallel via ajax kinda killed performance. The first ajax request as lightning fast but the rest just hung there. The one-by-one approach looked much better in my local env. Also, given that that page is a bit long depending on the number of projects, loading projects one-by-one fills the page accordingly.

frontend: compare: improve compare load times

---

squad/core/history.py
squad/core/models.py
squad/frontend/templates/squad/test_history.jinja2
test/core/test_history.py
test/frontend/test_history.py

This does improve load time but increases the number of queries depending on how many test runs. Although it seems silly, doing so will prevent production from spending too much time joining tests x test_runs x builds

frontend: test_history: improve load time

---

squad/api/rest.py
test/api/test_rest.py

An update in django filters made ProjectFilter switch queryset from Build/Environment/etc and Project, crashing requests filtering builds by project's full_name.
This patch makes sure to use correct field name based on queryset model

api: rest: fix project filter

---

squad/frontend/templates/squad/_results_table.jinja2

Fix hyberlinked url to point to test history in results table in
'Compare Builds' view.

frontend: fix test result url to point to history

---

squad/api/rest.py
test/api/test_rest.py

This fixes the issue where "/api/testruns/2997715/status/?suite=54959" wouldn't filter correctly.

api: rest: add filterset_class attribute to StatusViewSet

---

squad/plugins/linux_log_parser.py
test/plugins/test_linux_log_parser.py

This was the only spot in squad that wasn't creating a suitemetadata for tests.
I'm thinking about creating a migration to fill up all empty suitemetadata, but doing so would take a couple of hours (I've tested in testing db)

plugins: linux_log_parser: create metadata

---

squad/settings.py

This apparently make easier to identify when bugs got introduced depending on the release: https://docs.sentry.io/workflow/releases/

settings: init sentry plugin with squad release

---

squad/core/management/commands/fill_test_metadata.py
test/core/test_fill_test_metadata_command.py

Closes https://github.com/Linaro/squad/issues/792
This will allow filling SuiteMetadata into tests which have metadata == NULL

core: commands: add fill_test_metadata command

---

squad/frontend/templates/squad/index.jinja2
squad/frontend/views.py

Closes https://github.com/Linaro/squad/issues/798
This will split groups into three categories:
- active groups
- inactive groups (don't know if the term is too strong)
- user groups (groups starting with '~')
and it looks like this:

frontend: home: separate groups by active, inactive and usernamespaces

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

When resubmitting a test job automatically only global backend settings
were used. This patch uses Project settings as preferrence and only
defaults to global backend settings when Project doesn't define a
variable

ci: lava: ensure project settings take priority

---

squad/api/ci.py
squad/api/rest.py
squad/api/views.py
squad/ci/models.py
squad/core/admin.py
squad/core/tasks/__init__.py
squad/core/utils.py
test/api/test_ci.py
test/api/test_rest.py
test/api/tests.py
test/ci/test_models.py
test/core/test_tasks.py

When user creates/changes/deletes an object using API new LogEntry
object is created. LogEntry objects are available in the admin view.
Fixes: #202, #473

api: log user actions as LogEntry

---

squad/frontend/queries.py

We need to get all the test runs in a project. It takes far less time
if we do not use join on the testrun table.

Use WHERE IN instead of INNER JOIN for test run query in metrics.

---

squad/ci/templatetags/filter_jobs.py
squad/frontend/templates/squad/build-nav.jinja2
test/frontend/test_basics.py

Users complained that the "Test jobs" tab in the build view showed zero jobs, but when clicked, it showed a list of jobs.
This happened due to the way that tab was being counted. It didn't count jobs which "job_status=null".
This patch changes it so that it includes all test jobs despite of their status

frontent: build: include test jobs with no status in Test jobs tab

---

doc/install.rst
squad/settings.py

In setups where Sentry is configured, error emails might no longer be necessary. This patch checks an environment variable to decide whether or not send error emails to admins.

settings: add option to turn off admin error emails

---

squad/core/migrations/0139_nullable_test_name.py

Fixes
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0138_nullable_test_name, 0138_metric_unit in core).
To fix them run 'python manage.py makemigrations --merge'
```

core: migrations: "rebased" migration to make test name nullable

---

doc/plugins.rst
squad/core/models.py
squad/plugins/gerrit.py
test/core/test_project.py
test/plugins/test_gerrit.py

Fixes https://github.com/Linaro/squad/issues/867
Project settings should include:
```yaml
...
plugins:
gerrit:
build_finished:
success:
Code-Review: "+1"
Validation-Bot-Review: "+1"
error:
Code-Review: "-1"
My-Custom-Bot-Review: "-1"
...
```

Gerrit support custom tags

---

squad/core/templates/squad/notification/diff.html.jinja2

Fix broken testrun logs links in html notification.
Fixes: #864

core: templates, notification. Fix broken links

---

Dockerfile
requirements.txt
squad/core/utils.py
test/core/test_utils.py

The improvement will fix a long-running issue that happened when running tests. The Gerrit plugin used encrypt, which xor'ed password against Django's secret key. Depending on values, the generated value might contain null characters in between the string. While Python's OK with that, DB complained about it, thus raising an exception.

core: utils: improve cryptographic functions

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

The LAVA REST API returns the test result metadata as a string,
contrary to the XMLRPC. We need to yaml load if the metadata
is a string.

Parse results always expects metadata as a dict.

---

squad/frontend/views.py

This commit https://github.com/Linaro/squad/commit/6ced55dd78fd61dd26827d8df24c1e990da7eb0f has introduced attachment downloads, it also makes the frontend prefetch attachments blindly, which contains `data` field where all data resides. This PR avoids loading this data, only attachment name is needed.

frontend: views: avoid loading attachment data

---

doc/install.rst
requirements.txt
setup.py

Fixes https://github.com/Linaro/squad/issues/878
Installing SQUAD requires psycopg2 even if the setup is used with sqlite only. This patch makes installing squad avoid installing
postgres drivers. Run `pip install squad[postgres]` to have pip download psycopg2.

setup: make postgres optional

---

squad/api/rest.py
squad/api/utils.py
test/api/test_rest.py

This times out: https://qa-reports.linaro.org/api/testruns/3202175/tests/

api: improve testrun tests load times

---

squad/frontend/views.py

This was missing which caused test details view to fail if suite slug contained '$'. Exposed by #876

frontend, views: fix suite parsing in test details

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py
test/ci/backend/test_real_lava.py

When retrieving results from LAVA, REST API gives different results than
XML-RPC. The issue is described in LAVA ticket:
https://git.lavasoftware.org/lava/lava/-/issues/449
This patch addresses the problem with 'unit' vs 'units'.

ci: work around LAVA REST error

---

doc/conf.py
doc/plugins.rst

Quotes in gerrit plugin doc caused a misconfiguration to happen, this PR makes sure that quotes look just like the way they were supposed to look and also make gerrit yaml configuration look like yaml syntax.

Fix doc quotes

---

squad/core/management/commands/migrate_attachments.py
squad/core/tasks/__init__.py
test/api/tests.py
test/core/test_tasks.py

Inspired from https://github.com/Linaro/squad/pull/850
This PR makes use of storage fields without removing legacy ones. The intention is to start saving data to both DB and S3 so that when migrate legacy data to S3 we'll be sure that no data will be lost.
Next step will be replacing db data by S3 data.

Use storage

---

squad/core/tasks/notification.py
test/core/test_tasks_notification.py

When plugin is still running on the build, but the ProjectStatus for
this build is marked as finished, delay sending notification until
timeout or until the plugin finishes (whichever comes first)

core: delay notification if there are PluginScratch-es

---

squad/api/rest.py

These aren't useful for the enduser and they'll be abstracted by their non-storage siblings.

api: rest: hide storage fields

---

squad/ci/models.py
test/ci/test_tasks.py

TestJobs that received TemporaryFetchIssue and are successfuly fetched afterwards still keep the failure in them. This patch makes sure to clear any failure on successful fetches.

ci: models: clear TestJob.falure on successful

---

squad/api/rest.py

This will make build listing about 50x (sometimes 100x!) faster and reduce amount of time on project and suitemetadata listings.

api: rest: make build, project and suitemetadata listings faster

---

squad/ci/tasks.py

This will log SubmissionIssue as warning. TemporarySubmissionIssue will be saved (temporarily) to TestJob.failure. The intention is to leave Lava instability errors as warning only. Thoughts? There's a similar PR in squadplugins https://github.com/Linaro/squadplugins/pull/34

ci: tasks: submit: log message as warning instead of error

---

squad/ci/backend/lava.py
squad/ci/models.py
test/ci/backend/test_lava.py
test/ci/test_tasks.py

Cleaning TestJob.failure outside of Backend.get_implementation() can hide backend-specific errors.

ci: lava: clear TestJob.failure in backend implementation

---

squad/api/rest.py
test/api/test_rest.py

Fixes #903. Enable filtering specific fields for queried objects.

api, rest: enable filtering specific fields

---

squad/settings.py

From Sentry we've got `Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE`. It defaults to 2.5MB according [docs](https://docs.djangoproject.com/en/3.1/ref/settings/#data-upload-max-memory-size). This PR just increases it to 10MB, which I think it's a fine number.
BTW this error was generated when a user tried to submit 5MB of data.

settings: increase max upload size to 10MB

---

squad/api/rest.py
test/api/test_rest.py

Really fix https://github.com/Linaro/squad/issues/634
This is the first of a series of PRs I'm working on that makes use of https://github.com/Linaro/squad/pull/922
This adds a nested `tests` to the builds endpoint. So making queries like `/api/builds/1/tests` will return all tests from that build.

Add build tests api

---

squad/ci/backend/lava.py

Fix https://github.com/Linaro/squad/issues/919
For some reason, requests library doesn't raise 408 Timeout as exception, which causes submit to return empty list of ids and
causing IndexError.
This patch explicitly checks if requests returns 408 and handle that as TemporarySubmissionIssue

ci: backend: lava: handle HTTP 408 as TemporarySubmissionIssue

---

squad/core/management/commands/fix_squadplugin_data.py

A pattern has been identified for all buggy suitemetadata introduced
by the tradefed bug. The suite start with either 'armeabi*' or 'arm64*'.
Using this the command has been rewritten to execute faster. This should
be the best we have in hand right now.

core, commands: 4th attempt to make faster fix

---

squad/api/rest.py

Turns out that using build_id to order Test using CursorPagination is not a good idea, since there could be a situation where the "next" page is exact the same as the current one, thus giving an endless list of tests for clients like squad-client.

api: rest: order tests by id instead of build_id

---

squad/api/rest.py
squad/core/models.py
test/api/test_rest.py

Since @amrohassaan enabled field selection, the tests endpoint gained  a great speed improvement.
Getting 1000 tests used to take ~1s, then if only name/status selected, it takes ~500ms.
The solution was almost good enough, it still made queries to DB to fetch all the fields and just after it get removed before rendered to json.
This PR squeezes out a few extra ms by checking which fields are being requested to reduce DB prefetched and data loading.
Getting 1000 tests with only name/status takes now ~100ms.
I don't think doing the same for all endpoints is necessary, given that tests might be the endpoint with most access.

Enhance test field selection

---

squad/api/rest.py
test/api/test_rest.py

In cases were users are using "fields" to select build-specific fields, we might avoid loading unecessary data into memory, thus
saving serialization time.
Running a few local tests, fetching 1000 builds with all fields took about ~1s, while fetching version only took ~50ms.
This can make a huge difference when users fetch builds often.
Similar to https://github.com/Linaro/squad/pull/938, but for builds.

Enhance build field selection

---

squad/core/comparison.py
squad/core/models.py
test/core/test_history.py
test/core/test_metric_comparison.py
test/core/test_test_comparison.py
test/frontend/test_comparison.py

This PR improves TestComparison when it's used for regressions and fixes only. If it's used for applying transitions, the code will still use legacy load-all-in-memory.
It fixes half of https://github.com/Linaro/squad/issues/906. I say half because I couldn't find a way to apply all transitions in one trip to DB, especially `n/a - any other` and `any other - n/a`.
Also, this accidentally fixes https://github.com/Linaro/squad/issues/609. It turns out that current comparison will do something funny when the same test is run for the same build/environment. I can't say for sure why it does that, maybe a failed test gets overwritten by a passing one.

core: comparison: use raw sql to get regressions and fixes

---

squad/core/comparison.py
test/core/test_test_comparison.py

After https://github.com/Linaro/squad/pull/929 got merged, I tried it in staging with the following parameters:
Target: https://qa-reports.linaro.org/lkft/linux-stable-rc-linux-5.8.y/build/v5.8.18/
Baseline: https://qa-reports.linaro.org/lkft/linux-stable-rc-linux-5.8.y/build/v5.8.17-71-g46e8244bb94f/
And got the following results
Regressions:
- x15:
- ltp-tracing-tests/ftrace-stress-test - OK
- qemu_arm:
- ltp-tracing-tests/ftrace-stress-test - OK
+ **ltp-controllers-tests/memcg_subgroup_charge - NOT PRESENT IN qa-reports (fixed in this PR)**
- qemu_arm64:
- ltp-fs-tests/read_all_proc - OK
+ **ltp-controllers-tests/memcg_subgroup_charge - NOT PRESENT IN qa-reports (fixed in this PR)**
- x86:
- kselftest-vsyscall-mode-native/x86.fsgsbase_64 - OK
- hi6220-hikey:
- …

core: comparison: fix regression detection

---

squad/ci/management/commands/listen.py

Fixes https://github.com/Linaro/squad/issues/931
We check for changes in Backend models every 5s, and it probably take half of that just to run the query. This patch increases that poll interval to 1min as it's not something that changes that often

ci: listen: increase backend check poll to 1 min

---

squad/api/rest.py
test/api/test_rest.py

Use `regressions_and_fixes_only=True` for comparing bulds from the same projects using the API.

Use lighter version of TestComparison

---

squad/api/urls.py
squad/api/views.py

This will be useful for clients that need to check which version of SQUAD they're running against to.
To be addressed in https://github.com/Linaro/squad-client/pull/103

api: add version endpoint

---

squad/api/rest.py
squad/core/comparison.py
squad/core/history.py
squad/core/queries.py
squad/frontend/templates/squad/_results_table.jinja2
squad/frontend/templates/squad/compare.jinja2
squad/frontend/templates/squad/test_history.jinja2
squad/frontend/templates/squad/test_run_suite_test_details.jinja2
squad/frontend/templates/squad/tests.jinja2
squad/frontend/tests.py
squad/frontend/views.py
test/core/test_test_comparison.py

Multiple test results can occur during job resubmission.
Handle them correctly in various pages accross the system.
API and notifications update will be part of the later patch.

Handle multiple test results.

---

Dockerfile
requirements.txt
squad/core/models.py
squad/frontend/templates/squad/login.jinja2
squad/frontend/templatetags/squad.py
squad/settings.py
squad/socialaccount.py
squad/urls.py

Fixes https://github.com/Linaro/squad/issues/829
Answering @mwasilew questions:
> should we combine user accounts using different auth methods? For example if I have Linaro account and github account, should they be combined so I could authenticated with either provider?
That could be done, but I'm going with **no**. I don't think a user being logged in via Github/Gitlab should be authenticated as any Linaro user. It feels wrong, dunno why.
> do we even want to allow multiple auth providers at the same time?
That's done! Users can authenticate via Github or Gitlab
> how to manage access to projects for users with different auth providers (this is mainly for qa-reports.l.o)
Users will be granted default `squad` permissions, allowing them to create their own user space and with that they …

socialaccount: add Github and Gitlab social account login

---

Dockerfile
dev-docker

This update will upgrade the following important packages:
- Django will go from 1.11 to 2.0
- Python will go from 3.6 to 3.9
- Allauth will stay at 0.42 (which doesn't have a bug with Github login)
A few packages that were being installed via pip are now available in
Debian packaging system.
Some packages were dropped therefore removed from dev-docker.
NOTE: because now chromium is no longer in Debian Bullseye, we won't
be doing JS tests in dev-docker. They will still be run in travis though.

Dockerfile: update debian from buster to bullseye

---

Dockerfile
dev-docker

I upgraded our debian base docker image to bullseye in order to get newer packages, but mainly to satisfy django-allauth's requirement of having Django 2.2. Doing so proved to cause some compatibility issues mainly with boto and ldap connections.
I reverted that commit and started using -backports instead.

Rollback debian bullseye

---

squad/core/notification.py
test/core/test_notification.py

This prevents gerrit notifications from being sent on every new coming testjob

core: notification: mark as notified even if no recipients available

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

There's a scenario where a TestJob might not have the job_id when resubmit is requested, causing a crash.
This patch checks for that and submits the TestJob instead of trying to resubmit.

ci: lava: fix resubmit on testjobs with empty job_id

---

squad/core/queries.py
squad/frontend/tests.py

Build's all test results were a bit slow due to changes made in https://github.com/Linaro/squad/pull/937, this PR changes `test_confidence()` function to calculate the confidence offline if a list of tests is already provided.

frontend: tests: improve performance loading all test results

---

squad/core/comparison.py
squad/core/notification.py

Passing `regressions_and_fixes_only=True` to TestComparison will force it to use a fast way to compute regressions and fixes
thus improving performance of overall Notifications
I'll run a bigger round of tests before we can merge this.

[Don't merge it yet] core: notification: use fast TestComparison

---

squad/api/ci.py
test/api/test_ci.py

This patch let users disable environments in projects, thus avoiding test job submissions to such environments.
It's a WIP because it needs some extra discussion.

Use `expected_testruns == -1` to disable and environment for receiving new submissions

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

Fix https://github.com/Linaro/squad/issues/988
By not handling Timeouts, TestJob.fetch_attempt was never increased so the job would be retried over and over and over.
Now with correct exception handling, Backend.fetch() will correctly increase TestJob.fetch_attempts whenever there's a Lab downtime.

Raise TemporaryFetchIssue on fetch timeout

---

Dockerfile
setup.cfg
squad/frontend/templates/squad/_user_menu.jinja2
squad/urls.py

This package allows simple system checks to be made in a running SQUAD instance. The full configuration should take place in an external set up file.
This is how it's going to look:
For more information, please read:
https://django-health-check.readthedocs.io/en/stable/readme.html#

add suport to django-health-check

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

Sometimes LAVA might not populate all the metadata as expected. This patch makes sure not to break when suck scenario is reached.
@stevanradakovic @ivoire do you know if this value has changed in recent LAVA releases? I spot dozens of thousands of errors like that starting last week

ci: backend: lava: handle null error_msg

---

squad/api/rest.py

This patch enables updating TestJob.definition field using REST API.
Before that it wasn't possible. 
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

api: Allow to update TestJob definition via API

---

squad/frontend/templates/squad/testjobs.jinja2

Fix https://github.com/Linaro/squad/issues/997
This patch will disable the "resubmit" option of jobs that already got resubmitted. Things will look like this:
The patch also hides the "cancel" button on Jobs that are fetched already (it only makes sense to cancel jobs that aren't yet finished)

Disable resubmit button

---

squad/api/ci.py
test/api/test_ci.py

This patch adds a fetch task immediately as a job is triggered for watching, thus causing watched jobs to be fetched right away.

Fetch job as they are watched

---

doc/api.rst
squad/ci/models.py
test/ci/test_models.py

Fix https://github.com/Linaro/squad/issues/996
This patch checks whether the setting `CI_DELETE_RESULTS_RESUBMITTED_JOBS` is enabled, if so, delete the test run associated with the TestJob.
This will be useful for projects that need to resubmit jobs from whatever reason.

ci: models: delete results from resubmitted jobs

---

doc/api.rst
doc/ci.rst
squad/ci/models.py
squad/core/models.py
test/ci/test_models.py

Currently, job submissions/resubmissions on finished builds DO NOT retrigger email/patchsource/callback events.
This patch adds the new project setting `CI_RESET_BUILD_EVENTS_ON_JOB_RESUBMISSION` that when enabled, tells SQUAD to reset the events flags so that the next time a build finishes, events DO get triggered.

Allow resetting build events

---

squad/api/rest.py
squad/core/models.py
squad/frontend/ci.py
squad/frontend/static/main.css
squad/frontend/static/squad/build.js
squad/frontend/static/squad/controllers/testjobs_progress.js
squad/frontend/templates/squad/build.jinja2
squad/frontend/templates/squad/testjobs_progress.jinja2
squad/frontend/views.py
test/api/test_rest.py
test/core/test_build.py
test/frontend/test_basics.py

This patch allows SQUAD users to follow up which testjobs for a given build are completed, failed, running or still queued.
Below is a snapshot of how it looks like:
And below is another snapshot of the same view, this time for each environment:
I have also added an interval function in the browser that keeps updating the progress bar every MINUTE until the progress is 100%.

View testjobs progress

---

squad/core/models.py
squad/frontend/failures.py
squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templates/squad/failures.jinja2
squad/frontend/urls.py
test/core/test_build.py
test/core/test_test.py

It is difficult to tell if a test failure is a true regression or a
flakey test. To try and address this, we create a new view of test
failures for a build that displays a confidence score.
A confidence score is the ratio of the number of times the test has
passed over some number number of times the test has been run.

frontend: failures: compute a confidence score

---

squad/core/models.py
test/core/test_build.py

If this is the first time a test ran and it failed, there is no test
history to generate a confidence score from.
Return a score of zero for this case.

core: models: return a zero confidence score if there is no history

---

squad/core/models.py
squad/frontend/metrics.py
test/core/test_metric.py

The "All Metrics" page was way too slow, it was due to a missing prefetch on SuiteMetadata to retrieve the metric's name.

frontend: metrics: prefetch metric's metadata

---

squad/core/failures.py
squad/core/models.py
squad/frontend/failures.py
squad/frontend/templates/squad/failures.jinja2
test/core/test_build.py
test/core/test_failures.py

Use the FailuresWithConfidence class to control database access,
pagination, and searching for the failures view.
This class provides these features to improve performance when gathering
failing tests and their confidence score.

Add pagination to failures view

---

squad/plugins/linux_log_parser.py
test/plugins/linux_log_parser/oops.log
test/plugins/linux_log_parser/rcu_warning.log
test/plugins/test_linux_log_parser.py

This will split linux log parser tests into 2 different suites: `linux-boot-log-parser` and `linux-test-log-parser`. The first suite will contain matches of kernel failures during boot whereas the second one will contain matches after boot.
* linux-boot-log-parser:
* linux-test-log-parser:

plugins: linux-log-parser: split boot log

---

squad/api/rest.py
squad/core/failures.py
squad/frontend/failures.py
squad/frontend/templates/squad/failures.jinja2

SQUAD was comparing the history with the past N builds, and because not necessarily a build has the test in it, this could cause variations on the "count" in the UI.
Now it'll query the past N number of tests x environment that ensure that the count number is always equals to N.

core: failures: query past N tests instead of builds

---

squad/ci/backend/tuxsuite.py
test/ci/backend/test_tuxsuite.py

When tests fail due to failed build, neither logs or results are available, thus generating 404 responses. This patch handles such cases, assigning the "build failed" text to the TestJob.

ci: tuxsuite: handle failed tests

---

squad/api/rest.py
test/api/test_rest.py

This will allow filtering jobs by backend types, such as lava or tuxsuite

api: rest: add allow filtering testjobs by backend

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

The 500 errors were getting caught only for xmlrpc protocols. On /api protocols, 500 erros caused an empty list of testjob
ids.

Catch submission errors on 500 errors

---

squad/core/queries.py
test/frontend/test_basics.py

The extra order_by was left there probably due to a mistake. And that was causing an error since datetime is not a field of BuildSummary.

core: queries: remove extra order_by

---

squad/ci/backend/tuxsuite.py
test/ci/backend/test_tuxsuite.py

Sometimes, Tuxsuite might run into internal bugs when running tests. Squad should detect such cases and retry fetching results
later on.

ci: tuxsuite: retry fetching buggy Tuxsuite tests

---

squad/core/comparison.py

Without the `DISTINCT` keyword, the query might return duplicate rows due to same test/metric be present in more than one testrun.
By adding a distinct, the duplicates go away, thus reducing the amount of memory to populate python objects.

Remove duplicates in queries when computing regressions and fixes comparison

---

squad/ci/backend/tuxsuite.py
test/ci/backend/test_tuxsuite.py

The behavior for retrying was relying on any result being "unknown", but that does not make sense when the boot already failed.
This patch makes sure to retry fetching a TuxSuite job only in case of an unknown boot result.

Give up fetching when TuxSuite boot fails

---

squad/frontend/urls.py

Return HTTP 401 and its custom page when accessing forbidden/not visible content (similar to a 403).

urls: return 401 page on forbidden page access

---

squad/core/plugins.py
squad/frontend/templates/squad/build-nav.jinja2

When submitting annotation from UI it requires reverse API URL as a
parameter. Previous implementation only send Build object ID. It
resulted in a HTTP 400 response. This patch fixes the issue and provides
full reverse URL for the Build object API.
Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

frontend: fix reverse url for annotations UI

---

squad/frontend/urls.py
squad/frontend/views.py
test/frontend/test_basics.py

When data is submitted via the API, there is currently no structured way
to obtain the internal build ID so that it can be used for API requests.
Add an URL at /<project>/<build>/build/<version>/api/ that will redirect
to the correct API endpoint for the given build, i.e. /api/builds/<id>/.

frontend: build: add redirect URL to get API URL

---

squad/api/views.py
test/api/tests.py

Currentlty, an invalid date will cause an unhandled exception.

api: add_test_run: signal invalid request on validation errors

---

squad/api/ci.py
squad/ci/backend/fake.py
squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/models.py
test/api/test_ci.py
test/ci/backend/test_lava.py

There wasn't any checks against the job definition being submitted.
Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>

api: ci: reject job submission with malformed definition

---

squad/plugins/linux_log_parser.py
test/plugins/linux_log_parser/kernelexceptiontrace.log
test/plugins/test_linux_log_parser.py

There's a new multi-line warning that looks like this:
[    1.143924] ------------[ cut here ]------------"}
[    1.146063] WARNING: CPU: 0 PID: 1 at kernel/smp.c:912 smp_call_function_many_cond+0x3c4/0x3c8"}
[    1.146677] Modules linked in:"}
[    1.147156] CPU: 0 PID: 1 Comm: init Not tainted 6.0.0-rc3-next-20220901 #1"}
[    1.147363] Hardware name: Generic DT based system"}
[    1.147556]  unwind_backtrace from show_stack+0x18/0x1c"}
[    1.147692]  show_stack from dump_stack_lvl+0x58/0x70"}
[    1.147776]  dump_stack_lvl from __warn+0xd0/0x144"}
[    1.147857]  __warn from warn_slowpath_fmt+0x64/0xbc"}
[    1.147941]  warn_slowpath_fmt from smp_call_function_many_cond+0x3c4/0x3c8"}
[    1.148071]  smp_call_function_many_cond from smp_call_function+0x34/0x3c"}
[    1.148177] …

plugins: linux_log_parser: make 'except-trace' multi-line regex

---

squad/plugins/linux_log_parser.py
test/plugins/test_linux_log_parser.py

This will take in any match of a given log-parser result and generate a SHA256 sum to append to the name of the regex.
The intention is to have the possibility to compare same warnings/panics/etc against any other instance of the same fault in other builds.
Signed-off-by: Charles Oliveira <charles.oliveira@linaro.org>

plugins: linux_log_parser: compute contents to generate unique naming

---

squad/core/management/commands/users.py

After upgrading Dockerfile to buster-backports in commit f778bc6 (included in version 1.34) and upgrading Django to version 2 all "squad-admin users" commands fail with:
```
File squad/core/management/commands/users.py", line 42, in __init__
super().__init__(cmd, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```
To fix that, check Django version to pass correct number of arguments
to `__init__()` from Django CommandParser.
How to reproduce the crash:
- Run latest (or any 1.34+ version) squad container:
```
$ docker run -it --entrypoint /bin/bash squadproject/squad
squad@d4381404d0e4:/$ squad --bind 0.0.0.0:${SQUAD_PORT} &
...
squad@d4381404d0e4:/$ squad-admin users add admin
Traceback (most recent call last):
File "/usr/local/bin/squad-admin", line 8, in …
```

core: commands: fix command users crash with Django 2

---

requirements.txt
squad/ci/backend/lava.py

LAVA has recently enabled websocket in favor of ZMQ. Newer instances running on the cloud no longer have ZMQ working, so now SQUAD should first attempt connecting to websocket and fallback to ZMQ if the first doesn't work.

ci: lava: add websocket listener

---

squad/plugins/github.py
test/plugins/test_github.py

Github API has changed since the plugin was created. The new URL fixes HTTP 404 status. It's still not ideal as it leads to the JSON object instead of the nice web UI.
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

plugins: Fix URL returned by github plugin to the UI

---

squad/frontend/templatetags/squad.py
test/frontend/test_template_tags.py

Templatetag for socialaccount discovery had a bug that crashed /login view. This patch fixes the bug and adds unit tests for this templatetag.

frontend: fix bug with socialaccount discovery

---

squad/core/models.py
squad/frontend/views.py
test/core/test_build.py

Change the important_metadata field so the items are displayed in the order from the "Important metadata keys" project setting rather than alphabetically sorting the list.

Change important_metadata to follow order from "Important metadata keys"

---

squad/frontend/templatetags/squad.py
test/frontend/test_basics.py
test/frontend/test_template_tags.py

If status was missing, this would previously cause a 500 error when loading the page, due to a RelatedObjectDoesNotExist error being raised when the project status function was called.
Now, add handling for the case where status is None, so the project_status will return None instead of raising an error.

frontend/templatetags: Add handling for missing status

---

squad/api/rest.py
test/api/test_rest.py
test/frontend/test_basics.py

WIP draft of support for accessing attachments. Adds an AttachmentViewSet so a hyperlink can be created.
Work in progress as I have not yet figured out how to combine the url and the filename to create a clickable link directly to the file.

api/rest.py: Add URLs to access attachments

---

squad/ci/backend/tuxsuite.py
test/ci/backend/test_tuxsuite.py

Add support for fetching the TuxSuite test metadata file and adding its data to the SQUAD metadata file for the given test.

ci/backend/tuxsuite.py: Support for fetching test metadata file

---

squad/ci/models.py
squad/ci/tasks.py
squad/settings.py
test/ci/test_models.py

The reason for having this is for deployments of SQUAD on auto-scalable systems such as Kubernetes. When the load in SQUAD is high, Kubernetes creates new replicas of workers to consume from the queue.
When the load is back to low, Kubernetes starts trimming workers no longer being used. There is a very specific corner case with this approach though.
When Kubernetes trims a worker, it sends SIGTERM to it and wait 30s by default for the worker to self terminate. In Linaro's deployment of SQUAD, there is a particular kind of test job that comes from Android CTS/VTS. They are huge and take a lot more than 30s to finish. If the worker is not finished by the 30s mark, Kubernetes sends SIGKILL to it and it dies abruptly, causing inconsistencies.
Yes we can increase the 30s timeout, but if SQUAD …

ci/tasks.py: offload testjob post processing to its own task

---

squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/backend/tuxsuite.py
squad/ci/models.py
squad/frontend/templates/squad/testjobs.jinja2

- Resubmit button removed for TuxSuite jobs
- Cancel button changed so it just cancels the SQUAD lookup of the result, but does not try to cancel in TuxSuite
- Removed the logic for TuxSuite job cancel as Charles said it is not up to date and does not work any more
- job_id removed from buttons to make them a more suitable size

squad/ci: Remove resubmit / cancel buttons in TestJobs page for Tuxsuite jobs

---

squad/api/rest.py
test/api/test_rest.py

Make it possible to filter test jobs on 'created_at' date.

api: rest: add filter created_at

---

squad/plugins/linux_log_parser.py
test/plugins/linux_log_parser/kernel_bug_and_invalid_opcode.log
test/plugins/linux_log_parser/oops.log
test/plugins/test_linux_log_parser.py

The plugin used to look oneliner regexes within multiliner matches, meaning more instances of tests being generated.
Now, the plugin does not look within multiliner matches.

Do not look oneliners twice

---

squad/ci/backend/lava.py
squad/frontend/templates/squad/tests.jinja2

This proposal adds the possibility to jump directly to the line of the testcase in the Lava log from the "Tests" tab by clicking on the "Test Info" modal view. It makes the analysis of an issue easier.
For this, it fixes the modal "Test Info" view from the build "Tests" tab, and adds the URL of the Lava log of the testcase in it.

Improve testcase show info
