Linaro/squad

squad/frontend/templates/squad/test_run.html
squad/frontend/views.py

frontend: sort metadata keys alphabetically

---

squad/frontend/templates/squad/build.html
squad/frontend/views.py

Build metadata is composed of all test runs metadata

frontend: add build metadata

---

squad/core/admin.py

core/admin: add force-project-notification action to admin

---

squad/core/notification.py

notifications: add metadata sorting by key

---

squad/core/comparison.py
squad/core/history.py
squad/core/models.py
squad/core/notification.py
squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt
squad/frontend/templates/squad/test_run.html
test/core/test_build.py
test/core/test_comparison.py
test/core/test_test.py

This pull request also includes a couple of fixes for several small annoyances
in the notification emails

List since when a failing test has been failing

---

squad/ci/backend/lava.py

ci: lava: fix log fetching

---

squad/core/models.py

core: Test ordering by name

---

squad/ci/models.py
squad/frontend/templates/squad/test_run.html
test/ci/test_models.py

ci: add job_url to TestRun metadata if present

---

squad/frontend/static/squad/resubmit.js
squad/frontend/templates/squad/build.html

frontend: fix resubmit JS code

---

squad/frontend/templates/squad/base.html
squad/frontend/templatetags/squad.py

frontend: display squad version in the base template

---

squad/frontend/views.py

frontend: show all builds in the project front page

---

squad/ci/management/commands/listen.py
test/ci/test_listen.py

fork()ed subprocess will share the database connection from the master
process, and this will cause errors due to having multiple processes
handling the same connection. The usual sollution for this is closing
the connection before fork()ing, but in this case the master process
also needs its own connection for even starting the subprocesses and
managing their lifecycle. So, we now spawn entirely new processes for
each listener.
This has the disadvantage of making the startup a little slower and
increasing memory consumption. However, we don't have much of a choice
unless we want to completely redesign how listeners work (e.g. by
restricting them from using the database), which is not viable at all at
the moment.

ci/listen: spawn listener processes without fork()

---

squad/frontend/templates/squad/group.html

Signed-off-by: Dan Rue <dan.rue@linaro.org>

QA-1709: missing red bar in group main page

---

squad/core/notification.py

Signed-off-by: Dan Rue <dan.rue@linaro.org>

squad/core: Allow subject template to use metadata

---

.dockerignore
Dockerfile
INSTALL.rst
squad/settings.py

TODO: document how to customize things (i.e. DB connection, etc) using
environment variables. Try to not duplicate the corresponding
documentation in INSTALL.rst.

Dockerfile: run out of the box

---

squad/frontend/static/main.css
squad/frontend/templates/squad/build.html

- Turn all tables into grids
- Separate Test results from Metrics
- Highlight test suites with failures

frontend: redesign the build page

---

squad/core/models.py
squad/core/tasks/__init__.py
test/core/test_tasks.py

core: don't overwrite ProjectStatus with earlier data

---

squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt
squad/core/templatetags/squad_notification.py
squad/core/utils.py
squad/frontend/templatetags/squad.py

Once this is applied and deployed, similar changes need to be done to any
custom templates in use.

Handle lists as metadata values in notification emails

---

squad/core/templates/squad/notification/diff.html
squad/core/templates/squad/notification/diff.txt
squad/core/templatetags/squad_notification.py
squad/core/utils.py
squad/frontend/static/main.css
squad/frontend/templates/squad/_builds_table.html
squad/frontend/templates/squad/_project_list.html
squad/frontend/templates/squad/base.html
squad/frontend/templates/squad/build.html
squad/frontend/templatetags/squad.py

Several UI improvements

---

squad/frontend/static/main.css
squad/frontend/static/squad/filter.js
squad/frontend/templates/squad/_builds_table.html
squad/frontend/templates/squad/_metadata.html
squad/frontend/templates/squad/_project_list.html
squad/frontend/templates/squad/build.html
squad/frontend/templates/squad/test_run.html
squad/frontend/templates/squad/testjobs.html
squad/frontend/templates/squad/tests.html
squad/frontend/tests.py
squad/frontend/views.py

- Test suites with failures are displayed on top
- Test suites without failures are hidden by default and can be toggled
- If there are no test suites with failures, everything is shown

frontend: prioritize display of failures and add filtering

---

squad/core/queries.py

The original query uses too much RAM, because for each data point, it
will load the associated test run and build objects just to be able to
query a couple of fields. Instead, we now pull only those fields
explicitly from the database.

core.queries: optimize query for "tests pass %" metric

---

squad/api/rest.py

api: add filter_fields to BuildViewSet

---

squad/core/management/commands/migrate_test_runs.py

In case there is a need to move test runs from one project to the other
the script can move them basing on matching environment. Example call:
./manage.py runscript migrate_test_runs --script-args \
env_slug=<environment slug> \
old_project_slug=<from project slug> \
new_project_slug=<to project slug>  --traceback

scripts: add script to migrate testruns between projects

---

squad/frontend/templates/squad/test_history.html

frontent: fix env label in tests history table

---

squad/api/rest.py

api: add ID field to objects returned by REST API

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

ci: lava: add more strings to automatic resubmit list

---

test/core/test_utils.py

Signed-off-by: Dan Rue <dan.rue@linaro.org>

test_utils.py: Add additional parse_name tests

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

This patch broadens the list of potential test job error messages that
qualify for automated resubmission. Also messages can now be added to
LAVA ci backend setting as regular expressions.

ci/lava: allow resubmitting LAVA Test failures

---

squad/frontend/templates/squad/build-nav.html
squad/frontend/templates/squad/group.html
squad/frontend/templates/squad/index.html
squad/frontend/templates/squad/project-nav.html
squad/frontend/templates/squad/test_history.html
squad/frontend/templates/squad/test_run.html
squad/frontend/templates/squad/test_run_suite_metrics.html
squad/frontend/templates/squad/test_run_suite_tests.html

The change touches many pages but is a simple one. I also cleaned up hyperlinks css classes so they are consistent across all the headers in squad. 
Signed-off-by: Anmar Oueja <sitummam@gmail.com>

Improve the readabiliy of the headers

---

squad/frontend/templates/squad/build-nav.html
squad/frontend/templates/squad/project-nav.html

Improved the visual presence of the build and project tabs by using Bootstrap pills. 
Signed-off-by: Anmar Oueja <sitummam@gmail.com>

Improved the visual presence of the build and project tabs

---

squad/api/rest.py
test/api/test_rest.py

When custom email template has syntax errors API will report them back
to the user with HTTP status code 500 preventing server side crash.

api: report issues with email templates without crashing

---

squad/api/rest.py

api: fix crash when accessing TestRun.Metrics

---

squad/ci/backend/lava.py

ci: lava: prevent password leaking in error messages

---

squad/ci/models.py
test/ci/test_models.py

In case TestRun with job_id equal to the processed TestJob is already
present in database, InvalidMetadata exception i raised. In such case
TestJob.fetched field was remaining set to False. This patch makes sure
the 'fetched' field is set to True. This prevents LAVA backend to
resubmit test job unlimited number of times.

ci: make sure test job is marked fetched

---

squad/frontend/templates/squad/_builds_table.html
squad/frontend/templates/squad/build-nav.html
squad/frontend/templates/squad/project.html

frontend: add indication of unfinished builds

---

squad/api/rest.py
squad/frontend/static/squad/compare.js

This PR should fix part of the problems described in #319

Improve search in compare

---

squad/frontend/templates/squad/user_settings/profile.html

Signed-off-by: Dan Rue <dan.rue@linaro.org>

Typo in user profile frontend

---

squad/frontend/templates/squad/test_run.html

frontend: fix test_run.html after changes to templatetags

---

doc/api.rst
doc/ci.rst
doc/index.rst
doc/intro.rst

REST API docs were described including hidded routes. Also basic
documentation was moved to more proper places.

doc: added docs on REST API

---

squad/ci/backend/lava.py
squad/core/admin.py
squad/frontend/templates/squad/testjobs.html

I made these while debugging an issue

Misc improvements

---

squad/api/rest.py

api: allow to filter ProjectStatus by last_updated field

---

squad/frontend/templates/rest_framework/api.html

api: add 'comparetest' to the api template

---

squad/frontend/static/main.css
squad/frontend/static/squad/charts.js

Add hard limit of 50 points for each env in chart.
Allow user to control % of shown points via range slider.
Fixes #200

frontend: Limit number of points in charts.

---

squad/frontend/static/squad/charts.js

Update formatDate method so it returns empty string in case
of defult x-axis values ([-1, 1] range).
Remove leftover debugging with alert().
Keep dataset filtering logic in one place.

Remove x-axis ticks in case of an empty result set.

---

squad/core/migrations/0052_recreate_projectstatus_data.py
squad/core/notification.py
squad/jinja2.py

core: fix incorrect notification template names

---

.gitignore
.travis.yml
doc/hacking.rst
package-lock.json
package.json
squad/frontend/static/squad/charts.js
squad/frontend/static/squad/compare.js
test/karma.conf.js
test/test_javascript.py
test/unit/test_charts.js
test/unit/test_compare.js
test/unit/test_filter.js
test/unit/test_resubmit.js

Add npm package files.
Add karma configuration file.
Add unit tests for angular js code.
Fixes #181

Unit tests for JS code.

---

squad/celery.py

This will help us track down excess use of RAM in the workers.

celery: log memory usage for tasks that use more than 1MB

---

squad/frontend/static/squad/build.js
test/unit/test_annotation.js

This was supposed to be part of the annotations patch but I'm
adding it in separate iteration.

Add jasmine unit tests for annotation controller.

---

squad/ci/backend/lava.py

the regex list for `lava_infra_error_messages` was being
compiled within the results loop, but we only need this done once.
Not a huge improvement but it helps a little in performance

ci/backend/lava.py: moved regex compilation off loop

---

squad/api/data.py
test/api/test_data.py

If the metrics is not specified, we should send the data for all metrics.

Make api/data returns all results if the metrics is not specified.

---

squad/frontend/templates/squad/build.jinja2

Show Test runs regardles of suites filtering.
Fixes #411

Filtering on build page should only apply to Suites.

---

squad/api/rest.py
test/api/test_rest.py

Fix report baseline

---

doc/intro.rst

Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>

doc: correct errata in curl example

---

squad/frontend/static/main.css
squad/frontend/templates/squad/tests.jinja2
squad/frontend/tests.py

Add a simple post form filtering to all test results page.

Add all test results filtering.

---

squad/frontend/static/squad/metric.threshold.js
squad/frontend/templates/squad/_threshold_table.jinja2
squad/frontend/templates/squad/thresholds.jinja2
squad/frontend/views.py

When adding/editing thresholds, metric name is now a select2 list
for user QOL.

frontend: Thresholds metrics name should be a select control.

---

squad/core/models.py
test/core/test_project_status.py

Fix previous build ordering in project status test comparison.

---

squad/frontend/templates/squad/_threshold_table.jinja2

Threshold add/edit/del were visible to non-logged users

squad/_threshold_table.jinja2: restrict admin controls

---

squad/core/history.py
squad/frontend/templates/squad/test_history.jinja2
squad/frontend/templates/squad/tests.jinja2
squad/frontend/tests.py

Add 'show info' message for failed test cases in test view.
Fixes LSS-369

Error output missing from failed test cases in tests view.

---

squad/frontend/static/squad/charts.js
squad/frontend/static/squad/compare.js
squad/frontend/static/squad/config.js
squad/frontend/static/squad/controllers/annotation.js
squad/frontend/static/squad/controllers/charts.js
test/unit/test_charts.js

- Fix broken tests regarding charts. Now both `ChartsController` and `ChartPanel` have `DATA` injected, instead of using global one, that makes testing easier
- Fix missing import in `compare.js`
- Fix wrong `content-type` setting in `config.js`

Fix a few javascripting

---

squad/frontend/templates/squad/builds.jinja2
squad/frontend/views.py

Not high priority, just thought it might be useful.

core/builds: add pagination to builds view

---

squad/ci/models.py
squad/frontend/templates/squad/testjobs.jinja2

frontend: prevent displaying 'secrets' from LAVA job definition

---

squad/api/data.py
squad/core/queries.py

Limit amount of data in api/data API call by date range.
Fixes #462

Add query result limit to api/data

---

squad/core/management/commands/update_project_statuses.py

Include date-end argument.
Setup sequential update of the objects.

Refactor project status rebuild command.

---

doc/install.rst
squad/core/management/commands/users.py

'squad-admin users' allows to manipulate user records from command line.

core: add 'users' management command

---

squad/core/migrations/0116_make_group_membership_unique.py

The migration will keep the membership with higher access.

core: remove duplicate memberships before making them unique

---

Dockerfile

* Switch to buster slim variant.
* Use a single RUN command to reduce the number of layers.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

docker: reduce image size

---

.gitignore
.travis.yml
babel.cfg
requirements-dev.txt
scripts/update-translation-files
squad/frontend/locale/django.pot
squad/frontend/templates/squad/_user_menu.jinja2
squad/frontend/templates/squad/base.jinja2
squad/frontend/templates/squad/index.jinja2
squad/frontend/templates/squad/login.jinja2
squad/settings.py

i18n: add initial infra

---

squad/api/rest.py
test/api/test_rest.py

api: fix serialization of Project.enabled_plugins_list

---

squad/core/notification.py

core/notification.py: add number of skipped tests to default email template subject

---

squad/core/notification.py
test/core/test_notification.py

Closes https://github.com/Linaro/squad/issues/192

core/notification.py: include metrics in context of email notifications

---

squad/frontend/project_settings.py

frontend/project_settingspy: add enabled plugins list to settings

---

squad/api/ci.py
squad/ci/models.py
squad/http.py
test/api/__init__.py
test/api/test_ci.py

Resubmit api auth

---

squad/api/rest.py
squad/frontend/comparison.py
squad/frontend/static/main.css
squad/frontend/static/squad/attach_select2.js
squad/frontend/static/squad/build.js
squad/frontend/static/squad/build_compare.js
squad/frontend/static/squad/build_list.js
squad/frontend/static/squad/controllers/build_compare.js
squad/frontend/static/squad/controllers/build_list_compare.js
squad/frontend/templates/django/rest_framework/api.html
squad/frontend/templates/squad/_builds_table.jinja2
squad/frontend/templates/squad/_test_results_table.jinja2
squad/frontend/templates/squad/base.jinja2
squad/frontend/templates/squad/build.jinja2
squad/frontend/templates/squad/compare_builds.jinja2
squad/frontend/urls.py

Closes #191 
Compare build page:
Compare build in build list:
Compare build in build page:

Add UI to compare 2 builds from the same project

---

test/karma.conf.js

Forgot this last reference of floatThead. See https://github.com/Linaro/squad/pull/549 for context.

javascript: changed floatThread to floatThead

---

squad/frontend/templates/squad/project_settings/delete.jinja2

There is no linking from Weblate onto here.
The only info presented is a link to [the docs](https://hosted.weblate.org/projects/squad/#information), which don't seem to lead here.

Spelling: Delete project

---

squad/frontend/utils.py
squad/frontend/views.py
test/frontend/test_utils.py

Order projects by name alphanumerically, as asked on IRC

frontend: order projects alphanumerically

---

squad/core/comparison.py
squad/frontend/comparison.py
squad/frontend/static/main.css
squad/frontend/templates/squad/_results_table.jinja2
squad/frontend/templates/squad/base.jinja2
squad/frontend/templates/squad/compare_builds.jinja2
squad/frontend/templates/squad/compare_projects.jinja2
test/core/test_metric_comparison.py
test/core/test_test_comparison.py

Add option for metric based comparison for builds/projects. It's using the same template from test comparison. It shows the mean, the standard deviation between parenthesis and the number of measurements when hovering on the table cell.

Metric comparison

---

squad/frontend/static/squad/controllers/compare.js

Fixes LSS-304: Compare Tests in squad clips name of test
This makes the select2 widget to adjust its size according to what's in it.

Fix long names widget

---

squad/api/rest.py

Replace "detail_route" decorator by "action(detail=True)". As of django-restframework >= 3.8,  the "detail_route" has been completely removed [1], causing SQUAD travis tests to break.
[1] https://www.django-rest-framework.org/community/3.8-announcement/#deprecations

api: rest: fix rest-framework detail_route

---

squad/core/management/commands/users.py

core: add management command to create/update auth tokens

---

doc/intro.rst
squad/ci/backend/lava.py
squad/core/data.py
squad/core/tasks/__init__.py
test/api/tests.py
test/api/tests_log.json
test/ci/backend/test_lava.py

LAVA test logs

---

squad/ci/backend/lava.py

ci: catch YAML ScannerError in LAVA backend

---

Procfile
dev-docker
scripts/rabbitmq-server

I have been using dev-docker recently and these changes make the experience a
lot better for me.

Improvements to dev-docker

---

.travis.yml

Since old PR seems closed, pushing new one with required changes. Added reuse as a test job in travis.yml

Added reuse as a test env in travis.

---

pytest.ini
squad/api/rest.py
squad/ci/models.py
squad/core/comparison.py
squad/core/history.py
squad/core/models.py
squad/core/plugins.py
squad/urls.py
test/core/test_test.py
test/test_architecture.py
test/test_code_quality.py

We are not switching over yet. This pull request just adds the necesssary
infrastructure, and fixes all of the deprecation warnings from Django and other
libraries that pytest presents by default.

Add support for running tests with pytest

---

squad/core/models.py
test/core/test_project_status.py

Delay calculation of fixes and regressions to after a build has finished status. This will reduce amount of time to run UpdateProjectStatus

core: ProjectStatus: delay fixes and regressions

---

squad/core/comparison.py
squad/core/models.py

Revert https://github.com/Linaro/squad/commit/252adf15f80139b42489e3e7ddee68bbeddc29f0 and https://github.com/Linaro/squad/commit/ae46386e07d5fcd3c915c7093764599d9b2b501b
These worked alright locally, but put just too much load in staging db.

Revert changes that overload db

---

.readthedocs.yml

doc: add configuration for readthedocs build

---

requirements-dev.txt
squad/settings.py
squad/urls.py
test/settings.py

This adds django's debug toolbar for development environments.
It helped me a lot in improving the API performance.

debug: add django debug toolbar

---

squad/frontend/tests.py
test/frontend/test_tests.py

This fixes the test results page with tests with no metadata and also makes it load a bit faster

Fix test results page

---

pytest.ini

We have improved to 79.01% since.

pytest.ini: bump minimal code coverage

---

squad/frontend/project_settings.py
squad/frontend/static/main.css
squad/frontend/templates/squad/project_settings/base.jinja2
squad/frontend/templates/squad/project_settings/environments.jinja2
squad/frontend/templates/squad/project_settings/index.jinja2

This enables handling environments in project settings UI tab. Here's a snapshot of how it looks like:

Environments in project settings UI

---

squad/api/rest.py

rest.py: show testrun id conditionally in api depending on calling
endpoint. Testrun id shows in test main ep while not from nested Test ep. AFAIK, the main hold back from having testrun id show in tests main endpoint was regression in db queries. Tests on this PR shows 0 regressions.

api: rest: show testrun id in test endpoint

---

squad/plugins/linux_log_parser.py
test/plugins/linux_log_parser/kernelpanic.log
test/plugins/test_linux_log_parser.py

Closes https://github.com/Linaro/squad/issues/658
I added a regex for "BUG:" logs and made kernel panic a oneliner

Improve linux log parser

---

squad/api/rest.py
test/api/test_rest.py

Add top level metric ep similar to tests.

core: rest: add top-level metric endpoint

---

doc/hacking.rst
squad/settings.py

Add support for deployments that use Sentry
ref: https://sentry.io

settings: add support to Sentry

---

doc/api.rst
doc/intro.rst

Been a while since i've been wanting to add a note on these. Close https://github.com/Linaro/squad/issues/459, https://github.com/Linaro/squad/issues/461 and https://github.com/Linaro/squad/issues/460

Improve docs

---

squad/frontend/templates/squad/_test_run_test.jinja2

frontend: add link to full log from test list page

---

squad/core/models.py

core: fix project counter display on index page

---

squad/api/rest.py

REST: add ID to all possible serializers and filters

---

squad/frontend/ci.py

This will decrease load times of testjobs views

frontend: ci: reduce number of queries for testjobs view

---

squad/api/rest.py
squad/ci/backend/fake.py
squad/ci/backend/lava.py
squad/ci/backend/null.py
squad/ci/models.py
squad/frontend/static/squad/build.js
squad/frontend/static/squad/controllers/cancel.js
squad/frontend/templates/squad/testjobs.jinja2
test/api/test_rest.py
test/ci/test_models.py
test/unit/test_cancel.js

Lava cancel

---

squad/core/models.py
squad/frontend/templates/squad/_project_list.jinja2
squad/frontend/templates/squad/_subscribe.jinja2
squad/frontend/templates/squad/project-nav.jinja2
squad/frontend/templates/squad/testjobs.jinja2
squad/frontend/user_settings.py
test/test_i18n.py

Subscribe ui fixes

---

squad/frontend/static/squad/controllers/annotation.js
test/unit/test_annotation.js

This fixes the error message "Undefined" reported by in https://github.com/Linaro/squad/issues/718

static: annotation: better handle error messages

---

squad/api/rest.py

api: add docstring to endpoints with additional methods

---

squad/api/rest.py
test/api/test_rest.py

Fixes https://github.com/Linaro/squad/issues/729

api: rest: handle null test_name in project/test_results

---

squad/ci/models.py
test/ci/test_models.py

ci: fix ProjectStatus processing in fetch()

---

CODEOWNERS

This should reduce inbox notifications

remove CODEOWNERS file

---

Dockerfile
requirements.txt
scripts/travis-lava
squad/ci/backend/lava.py
test/ci/backend/test_real_lava.py

ci: fix get_listener_url() in case of REST

---

.dockerignore
.gitignore
.travis.yml
Dockerfile
dev-docker
docker-compose.yaml
scripts/release
scripts/release-docker
scripts/test-docker
scripts/upload

This Dockerfile installs squad from a locally built package which prevents dev stuff from being packed into the image, and also packs squadplugins within.
The patch also updates docker-compose.yml so that all running containers use a shared database.

Dockerfile: improve Dockerfile

---

squad/api/rest.py
test/api/test_rest.py

expose an endpoint to compare two builds within same project and report
regressions and fixes.

api: rest, endpoint to compare two builds

---

squad/ci/backend/lava.py
test/ci/backend/test_real_lava.py

ci: lava: update backend implementation to ensure proper URLs

---

squad/frontend/views.py
test/frontend/test_basics.py

frontend: fix crash when paginator page is not found

---

squad/frontend/static/squad/controllers/filter.js
squad/frontend/templates/squad/_test_results_envbox.jinja2
squad/frontend/templates/squad/_test_results_suitebox.jinja2

frontend: fix filtering box in build view

---

squad/frontend/ci.py
squad/frontend/templates/squad/testjobs.jinja2

frontend: add pagination to testjobs view

---

squad/frontend/templates/squad/test_history.jinja2
squad/frontend/templates/squad/tests.jinja2
squad/frontend/tests.py
squad/frontend/urls.py

frontend: restore legacy test history url and redundant test result bug fix

---

squad/api/rest.py
squad/frontend/static/squad/controllers/compare.js
test/unit/test_compare.js

This improves query to test_results and also makes UI a bit faster

api: rest: make project/<id>/test_results faster

---

squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templatetags/squad.py

Fixes #746 adding a previous and next navigation buttons in build page.

frontend: add prev & next in build page

---

squad/frontend/templates/squad/_project_list.jinja2
squad/frontend/templates/squad/_subscribe.jinja2
squad/frontend/templatetags/squad.py
squad/frontend/views.py

This patch improves load times for group page from 1s to 0.2s and lower number of queries from 51 to 7.

frontend: improve group page load times

---

squad/frontend/views.py

Fix https://github.com/Linaro/squad/issues/769

frontend: views: fix page view for unauthenticated users

---

squad/frontend/templates/squad/_test_run_test.jinja2

frontend: add test history link in test list

---

squad/api/rest.py
test/api/test_rest.py

fixes #501. Add more detailed build summary breaken down by environment

api, rest: add more status details

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

ci: fix lava backend log download

---

squad/frontend/static/squad/controllers/build_list_compare.js
squad/frontend/templates/squad/_builds_table.jinja2
squad/frontend/templates/squad/build.jinja2

enable user to choose between metrics and tests when comparing builds in
project view and builds list view.
Fixes #598

frontend: add choice of comparison type

---

squad/frontend/static/main.css
squad/frontend/templates/squad/_test_results_envbox.jinja2
squad/frontend/templates/squad/_test_results_suitebox.jinja2
squad/frontend/views.py

Close https://github.com/Linaro/squad/issues/781
Here's a snapshot of what's looking like:

Add totals test results build view

---

squad/frontend/templates/squad/testjobs.jinja2

frontend: fix tooltips in testjobs page

---

squad/api/rest.py
squad/core/comparison.py
squad/core/history.py
squad/frontend/tests.py
squad/frontend/views.py
test/frontend/test_tests.py

This patch fixes remaining locations affected by removing test name column

core/frontend: fix side effects of removing test name column

---

Dockerfile
dev-docker
requirements.txt
squad/frontend/ci.py
squad/frontend/static/main.css
squad/frontend/templates/squad/testjobs.jinja2
squad/frontend/templatetags/squad.py

frontend: add filter to testjobs view

---

squad/settings.py

This will allow having i.e. django db options as part of the
database settings. Example {'options': '-c statement_timeout=5000'}.

Allow equal sign and dicts in django settings

---

squad/frontend/queries.py

Second part of the fix for #694.

Evaluate environment ids fetch query.

---

squad/settings.py

settings: add CeleryIntegration to sentry

---

squad/ci/backend/lava.py
test/ci/backend/test_lava.py

It's a potential fix for issues with pods hanging on pending requests to LAVA.

Lava xml requests transport

---

squad/core/migrations/0131_create_squad_auth_group_and_add_users.py
squad/core/migrations/0133_append_project_permissions_to_squad_auth_group.py
test/api/test_rest.py

Fixes: https://github.com/Linaro/squad/issues/835
Complements: https://github.com/Linaro/squad/pull/785

Add project object level permissions

---

squad/frontend/templates/squad/project_settings/delete.jinja2

Fix a typo on the delete project button

---

squad/frontend/templates/squad/knownissues.jinja2
squad/frontend/templates/squad/project-nav.jinja2
squad/frontend/urls.py
squad/frontend/views.py

Add knownissues tab to project/builds view.
Fixes #784.

Frontend,  add knownissues

---

squad/ci/admin.py
squad/ci/management/commands/testfetch.py
squad/ci/tasks.py
squad/ci/utils.py
test/api/test_ci.py
test/ci/test_tasks.py

This will help debugging tasks

ci: tasks: define task_id for fetch tasks

---

squad/frontend/static/squad/controllers/charts.js

Fixes #775, add download button with permalink to each chart in project metrics.

frontend: static, export metrics graphs as picture

---

squad/api/rest.py
test/api/test_rest.py

Really implements https://github.com/Linaro/squad/blob/1.22/squad/api/rest.py#L1085

api: rest: add tests endpoint to suite view

---

test/plugins/test_gerrit.py

test: fix gerrit unit tests

---

test/api/test_rest.py

Found this leftover print when I did a change in the suite api

test: remove leftover print

---

squad/api/rest.py

Fixes https://github.com/Linaro/squad/issues/704

api: rest: sandardize url-id in rest api

---

squad/http.py
squad/urls.py
test/api/test_ci.py

This should address https://github.com/Linaro/squad-client/issues/70

http: handle 404 as json on api requests

---

squad/settings.py

I made SQUAD_SEND_ADMIN_ERROR_EMAIL impossible to be false, this PR fixes that :)

settings: fix SQUAD_SEND_ADMIN_ERROR_EMAIL flag values

---

.dockerignore
.gitignore
Dockerfile
squad/core/migrations/0142_add_testrun_file_storage.py
squad/core/migrations/0143_attachment_storage.py
squad/core/migrations/0144_attachment_data_null.py
squad/manage.py
squad/settings.py
test/core/test_attachment.py
test/core/test_test_run.py
test/settings.py

Fixes migrations for PR https://github.com/Linaro/squad/pull/849 and add a few tests for it

Fix storage migrations

---

squad/core/management/commands/fix_squadplugin_data.py

clean bad suite in suitemetadata generated from tradefed

commands: add script to clean tradefed bad entries

---

doc/plugins.rst

docs: fix curl calls in plugins page

---

squad/plugins/gerrit.py
test/plugins/test_gerrit.py

Fix https://github.com/Linaro/squad/issues/894

plugins: gerrit: use same regex for split and match checks

---

squad/core/management/commands/migrate_attachments.py

Each thread might spawn multiple threads to make S3 uploads, thus causing OOM errors and `[WARNING] Connection pool is full, discarding connection` from urllib3.
Having 2 threads seems to be the sweet spot (tried with 4 and 8, but pod always gets killed)

core: migrate_attachments: reduce number of threads

---

squad/frontend/templates/squad/_subscribe.jinja2
squad/frontend/views.py

fronend: notification bug

---

squad/core/management/commands/fix_squadplugin_data.py

Rewrite the command to fix the corrupt data for the tradefed issue to
make it faster.

core: commands, rewrite command to fix tradefed

---

squad/core/history.py

Add None to all builds that don't have the test in test history so
it shows 'n/a' in test history view. The downside is it adds all the project environments even if they are not relevant.

core, history: add None to all builds

---

squad/api/rest.py

Fix a typo in the api docs

---

squad/core/comparison.py

Fixes https://github.com/Linaro/squad/pull/941 (already a fix)

core: comparison: fix regression detection

---

doc/ci.rst
squad/core/models.py
squad/core/notification.py
test/core/test_notification.py

This one will send notification to the recipient if any of the jobs
in the build have status "Incomplete".
Fixes #753

Introduce new notification strategy ON_ERROR.

---

squad/api/rest.py

This will avoid prefetching testruns when loading project's builds.

api: rest: enhance builds nested endpoint in projects endpoint

---

squad/frontend/group_settings.py

Fixes https://github.com/Linaro/squad/issues/972

frontend: group_settings: avoid timeout deleting groups

---

squad/frontend/project_settings.py

Fixes https://github.com/Linaro/squad/issues/970

frontend: project_settings: add important-metadata-keys

---

squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templates/squad/build_callbacks.jinja2
squad/frontend/urls.py
squad/frontend/views.py
test/frontend/test_basics.py

Fixes https://github.com/Linaro/squad/issues/973
And it'll look like this:

frontend: build_callbacks: add callbacks to the Build view

---

squad/frontend/templates/squad/build-nav.jinja2

Fixes https://github.com/Linaro/squad/issues/924

frontend: build-nav: add test summary to build header

---

squad/core/tasks/__init__.py
test/core/test_known_issues.py

This will allow known issues maintainers to provide pattern as test_name so that it can match multiple suites, or multiple tests
patterns.
For example, a known issue with test_name equals to `ltp-*/foo` will match ALL incoming new tests `ltp-syscalls/foo` or `ltp-timers/foo`. 
@nareshkamboju @roxell thoughts?

core: tasks: add support for patterns in known issue test_name

---

squad/api/rest.py
squad/core/models.py
squad/frontend/static/squad/controllers/metricThreshold.js
squad/frontend/templates/squad/build-nav.jinja2
test/api/test_rest.py

In this PR:
1. Add build, environment, and metadata filters to metrics endpoint
2. Add metrics nested endpoint for builds endpoit: /api/builds/<id>/metrics
3. Fixed @jscook2345 comments on https://github.com/Linaro/squad/pull/1006
4. Add a link in the build view to the build api view

Metric tweaks

---

squad/frontend/metrics.py
squad/frontend/templates/squad/build-nav.jinja2
squad/frontend/templates/squad/build_metrics.jinja2
squad/frontend/urls.py

all: add a page to view the metrics for a build

---

dev-docker
requirements-dev.txt
squad/ci/backend/lava.py
test/ci/backend/test_lava.py

This is a series of patches that deals with errors resulting from using LAVA's REST API.

Lava api errors

---

squad/api/rest.py
squad/frontend/static/squad/build.js
squad/frontend/static/squad/controllers/fetch.js
squad/frontend/templates/squad/testjobs.jinja2
test/api/test_rest.py

Authenticated users can now manually request a fech for a given job:
When clicking on "manual fetch", squad will enqueue the job again for fetching.

Force fetch

---

squad/frontend/failures.py

squad: frontend: failures: remove a duplicate line

---

squad/api/rest.py
squad/core/failures.py
squad/frontend/failures.py
squad/frontend/templates/squad/failures.jinja2
test/api/test_rest.py
test/core/test_failures.py

You'll have to fix up the tests, but I'm sure you'll be able to do that in no time at all. Thanks.

Add failures with confidence to rest api

---

squad/ci/backend/tuxsuite.py
test/ci/backend/test_tuxsuite.py

Set TestJob.name for TuxSuite builds and tests

Set names for builds and test jobs

---

squad/api/rest.py
test/api/test_rest.py

This will allow filtering builds by id "=<" and ">="

Allow filtering builds by id

---

squad/api/data.py
squad/core/models.py
squad/core/queries.py
squad/frontend/queries.py
squad/frontend/static/squad/controllers/charts.js
squad/frontend/templatetags/squad.py
squad/frontend/views.py
test/frontend/test_basics.py

This patch contains several improvements with regard to the metrics page:
* fix bug when displaying metrics of a project with no thresholds
* improve overall query performance
* fix bug of a disappearing chart when selecting an environment without metric data

Fix metrics page

---

squad/core/models.py
squad/core/tasks/__init__.py

This improves overall query performance when computing stats for testruns by avoiding loading tests in memory and instead computing it in the database.

Improve testrun status count

---

doc/api.rst
squad/frontend/badges.py
squad/frontend/urls.py
squad/frontend/views.py
test/frontend/test_basics.py

This allows generating badges with suite and environment as filter

Extend badges

---

squad/frontend/views.py
test/frontend/test_basics.py

Add a group parameter for filtering projects in a group home their age as an alternative to limiting by count.

squad/frontend/views.py: Add support for filtering project list by age
